### ISSUE TITLE
Circleci failing

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#106]
Somebody played with circleci tooling on the project.
The first thing this CI system is calling

mvn dependency:resolve

This is leading to this build error:
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google App Engine Runtime Parent ................... SUCCESS [  5.924 s]
[INFO] Google App Engine Logging Support .................. SUCCESS [  0.714 s]
[INFO] Google App Engine Image for OpenJDK ................ SUCCESS [  0.080 s]
[INFO] Google App Engine Image Jetty ...................... SUCCESS [  0.007 s]
[INFO] Google App Engine Runtime Support .................. FAILURE [  2.704 s]
[INFO] Compatibility test application ..................... SKIPPED
[INFO] Google App Engine Image for GAEv1 Java Compatibility SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.561 s
[INFO] Finished at: 2015-09-28T10:19:34+00:00
[INFO] Final Memory: 20M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project appengine-managed-runtime: Could not resolve dependencies for project com.google.appengine:appengine-managed-runtime:jar:1.9.26-SNAPSHOT: Could not find artifact com.google.appengine:appengine-java-logging:jar:1.9.26-SNAPSHOT in sonatype-google-releases (https://oss.sonatype.org/service/local/repositories/google-releases/content) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR] mvn <goals> -rf :appengine-managed-runtime

**Comment by gregw** [comment]
The problem is with [Multi-module Build Dependencies]( http://www.alexecollins.com/migrating-to-circleci/), will add a circle.yml to fix.

**Comment by gregw** [comment]
I've made a bit of progress in PR#108.  The circle.yml now is setup for multi-module build and it also configures openjdk8.  However it is now failing on the docker plugin step.

This may be because the build is actually happening during the dependency resolution step?

**Comment by gregw** [comment]
PR #108 now gets a clean build with circleci.

**Comment by gregw** [comment]
We are now hitting another circleci problem: docker/docker#9939

**Comment by gregw** [comment]
from circleci support:


Sent to sayhi@circleci.com, gregw@webtide.com

That error with chown comes from the fact that we are using LXC and cannot preserve the original ownership of tarred file. Unfortunately, the only solution is to ask maintainers of the Dockerfile to use "--no-same-owner" option in tar. I don't think using the option doesn't do any harms, so they will probably accept the change.

--
Hirokuni Kim 	Hirokuni Kim from Circle
On Fri, Oct 9, 2015 at 02:15 AM, "gregw@webtide.com" <gregw@webtide.com> wrote:

    Hirokuni,

    yes we do have definite problem that are not ignorable. See the failure in https://circleci.com/gh/GoogleCloudPlatform/appengine-java-vm-runtime/21

    The plugin is executing the docker file and running a tar extraction that fails to chown a file. This looks to be in associated with the filesystem error, but I guess it could be unrelated. Have a look at the debug output and tell me what you think?

    These builds work fine with normal builds.

    cheers
    On Fri, Oct 9, 2015 at 12:49 AM, "Hirokuni Kim" <hirokuni.kim@circle.mail.intercom.io> wrote:

        I see. However, the error is normally red-herring and you can ignore them. Do you have actual problems with not being able to remove containers?
        On Wed, Oct 7, 2015 at 09:38 PM, "gregw@webtide.com" <gregw@webtide.com> wrote:

            On 8 October 2015 at 12:42, Lev from Circle <lev.lazinskiy@circle.mail.intercom.io> wrote:

            Sorry about that! There is a problem being able to destroy containers on CircleCI, if you can skip this step by removing the --rm flag from the docker run command that would be the best solution for now. We are working on making this better in the future but if that doesn't work for you please let us know.

            Lev,

            unfortunately we can't do that as we are using the spotify maven docker plugin and it does not appear to have the option to add/remove the --rm flag.

            so the exact docker commands are beyond our control.

            cheers



            -- 

            Greg Wilkins <gregw@webtide.com> CTO http://webtide.com
            On Wed, Oct 7, 2015 at 06:42 PM, "Lev Lazinskiy" <lev.lazinskiy@circle.mail.intercom.io> wrote:

                Hi Greg, 

                Sorry about that! There is a problem being able to destroy containers on CircleCI, if you can skip this step by removing the --rm flag from the docker run command that would be the best solution for now. We are working on making this better in the future but if that doesn't work for you please let us know. 

                Best,
                Lev 
                On Wed, Oct 7, 2015 at 05:10 PM, "gregw@webtide.com" <gregw@webtide.com> wrote:

                    Google enabled circleci on their https://circleci.com/gh/GoogleCloudPlatform/appengine-java-vm-runtime, but it fails on my PRs eg.
                    https://circleci.com/gh/GoogleCloudPlatform/appengine-java-vm-runtime/21

                    It appears to be some error with docker:

                    Error removing intermediate container 1f3a1d541241: Driver btrfs failed to remove root filesystem 1f3a1d541241e757d48f34329508253e9ee139380b7b914a3b1104677eb0e8ee: Failed to destroy btrfs snapshot: operation not permitted

                    HELP!
