### ISSUE TITLE
New Master Breaks Bigtable Example

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/appengine-java-vm-runtime#107]
I am still debugging it but just a note that some recent changes were not backwards compatible and have broken this example:

https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/managed-vm-gae

As of my README update (07f3ec38b8bb93c35405168ed34b04dcd06383cb) it was working fine, now rebuilding the images, I am getting errors like: 

java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)

the index route gives a 503 timeout, although it works if I attach to the container. The healthchecks are also failing. Guessing it has something to do with prerun.sh not working the way it used to but I'm still looking into it.

**Comment by waprin** [comment]
Ok Jetty 92 branch works for me...

**Comment by ludoch** [comment]
Can you attach the entire errors or the output log?

**Comment by gregw** [comment]
I believe the 'java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)' warning is because the working directory is expected to be the webapp (or the env variable has not been set).

**Comment by waprin** [comment]
@gregw I have seen that problem before but then changed my directory to match the guestbook example, and it works in the jetty-92 branch so I think this is a different problem.

Also very interesting to note, is that if I use the boot2docker ip and then the port that Docker maps to, the web app does serve (although it can't connect to Bigtable due to "invalid grant", which I think means it doesn't have the credentials setup).

Using mvn gcloud:run, here are the `docker logs` of the container.

2015-09-29 03:28:02.986:INFO::main: Logging initialized @230ms
2015-09-29 03:28:03.298:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2015-09-29 03:28:03.324:INFO:oejs.AbstractNCSARequestLog:main: Opened /var/log/app_engine/request.2015_09_29.log
Sep 29, 2015 3:28:03 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:28:03 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_appengine_hostname' path retrieval error: metadata
Sep 29, 2015 3:28:03 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_use_nginx_proxy' path retrieval error: metadata
Warning: caught exception when reading logging properties.
java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)
2015-09-29 03:28:39.716:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2015-09-29 03:28:39.901:WARN:oejs.SecurityHandler:main: ServletContext@c.g.a.v.j.VmRuntimeWebAppContext@12cdcf4{/,file:///var/lib/jetty/webapps/root/,STARTING} has uncovered http methods for path: /*
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2015-09-29 03:28:54.987:INFO:oejsh.ContextHandler:main: Started c.g.a.v.j.VmRuntimeWebAppContext@12cdcf4{/,file:///var/lib/jetty/webapps/root/,AVAILABLE}
2015-09-29 03:28:55.007:INFO:oejs.ServerConnector:main: Started ServerConnector@30b7c100{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2015-09-29 03:28:55.007:INFO:oejs.Server:main: Started @52262ms
Sep 29, 2015 3:28:56 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:28:56 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:01 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:06 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:11 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:16 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:21 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:26 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 3:29:31 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
waprin-macbookpro:frontend waprin$

**Comment by waprin** [comment]
So to clarify, assuming boot2docker IP is `docker`, after mvn:gcloud run:

localhost:8080 gives 503 and above error message in logs.
docker:<docker port> serves the page but can't access Bigtable.

**Comment by waprin** [comment]
Also a big difference between what I'm doing is I used to use the ./buildimage.sh and now I'm using the Maven instructions as recommended.

**Comment by joakime** [comment]
you have several logging issues ...

> log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/var/lib/jetty/webapps/root/WEB-INF/lib/slf4j-jdk14-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

The problems present in those warnings ...

1. You have log4j in your environment, but haven't configured it.
2. Don't mix and match slf4j versions (use 1.6.1 or 1.7.7 for all slf4j dependencies)
3. If you want to capture java.util.logging -> slf4j -> slf4j-log4j -> log4j then drop `slf4j-jdk14-1.7.7.jar` and use `jul-to-slf4j-1.7.7.jar` instead.
4. Don't forget to setup the jul handler for slf4j too.  (which can be automatic with logback, but not log4j as your slf4j impl)
5. You are not capturing commons-logging -> slf4j -> slf4j-log4j -> log4j to do that, add `jcl-over-slf4j-1.7.7.jar` (and exclude the normal commons-logging jars)

**Comment by waprin** [comment]
Alright fair point I'll fix the logging issues and see if that provides any better info.

**Comment by waprin** [comment]
Ok I got rid of the errors except for not finding logging.config...that is the root of the problem after all.

2015-09-29 19:20:28.690:INFO::main: Logging initialized @174ms
2015-09-29 19:20:28.946:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2015-09-29 19:20:28.970:INFO:oejs.AbstractNCSARequestLog:main: Opened /var/log/app_engine/request.2015_09_29.log
Sep 29, 2015 7:20:29 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:20:29 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_appengine_hostname' path retrieval error: metadata
Sep 29, 2015 7:20:29 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_use_nginx_proxy' path retrieval error: metadata
Warning: caught exception when reading logging properties.
java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)
2015-09-29 19:20:50.455:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2015-09-29 19:20:50.563:WARN:oejs.SecurityHandler:main: ServletContext@c.g.a.v.j.VmRuntimeWebAppContext@12cdcf4{/,file:///var/lib/jetty/webapps/root/,STARTING} has uncovered http methods for path: /*
Sep 29, 2015 7:20:50 PM org.apache.hadoop.util.NativeCodeLoader <clinit>
WARNING: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Sep 29, 2015 7:20:50 PM com.google.cloud.bigtable.config.Logger warn
WARNING: Could not asynchronously create the ssl context, since ALPN is not installed.
Sep 29, 2015 7:20:51 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for projectId coinflow-demo, zoneId us-central1-b, clusterId coinbase, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
2015-09-29 19:21:01.450:INFO:oejsh.ContextHandler:main: Started c.g.a.v.j.VmRuntimeWebAppContext@12cdcf4{/,file:///var/lib/jetty/webapps/root/,AVAILABLE}
2015-09-29 19:21:01.463:INFO:oejs.ServerConnector:main: Started ServerConnector@13d73f29{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2015-09-29 19:21:01.466:INFO:oejs.Server:main: Started @32954ms
Sep 29, 2015 7:21:01 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:01 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:06 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:11 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:16 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:22 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:27 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:32 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:37 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:42 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata
Sep 29, 2015 7:21:47 PM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
INFO: Meta-data 'attributes/gae_affinity' path retrieval error: metadata

**Comment by waprin** [comment]
Ok I spoke with @lesv (leads Bigtable example project) about this, he had done some workarounds to get Bigtable working with this runtime at all, so it's not shocking it broke. He is fine with us just recommending jetty-92 branch while the dust settles around certain things like ALPN support, so this can be considered a low priority issue or closed or whatever.
