### ISSUE TITLE
FR: Add OpenSSL 1.0.2 to base image for Jetty 9.3

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#115]
@ejona86 
@ludoch 

Please add OpenSSL 1.0.2 to support faster gRPC http/2.  [see](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-openssl) for more info.

**Comment by gregw** [comment]
@lesv  I find the open ssl versioning a bit confusing.... so just double checking, will it be sufficient to install:
```
wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2d-1_amd64.deb \
         http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-1_amd64.deb \
 && dpkg -i openssl_1.0.2d-1_amd64.deb libssl1.0.0_1.0.2d-1_amd64.deb \
```

**Comment by lesv** [comment]
@sduskis you just went through this exercise.  Care to comment?

**Comment by ludoch** [comment]
ping?

**Comment by gregw** [comment]
@sduskis @lesv ping?

**Comment by lesv** [comment]
I believe so.

On Wed, Nov 18, 2015 at 6:29 PM, Greg Wilkins <notifications@github.com>
wrote:

> @sduskis <https://github.com/sduskis> @lesv <https://github.com/lesv>
> ping?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/issues/115#issuecomment-157897972>
> .
>



-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023
