### ISSUE TITLE
How to setup Cloud debugger and java opts passed via env with the OpenJDK8 image?

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#117]
Soon, the Cloud SDK will generate this dockerfile when you wan to deploy a .jar file (for example, SpringBoot app listening to port 8080):

    FROM gcr.io/google_appengine/openjdk8
    ADD foo.jar /app/
    ENTRYPOINT ["java", "-jar", "/app/foo.jar"]

What is the best way to customize it with ENV variables passed via docker build/run and enabling jvm opts and cloud debugger/profile?

**Comment by gregw** [comment]
@ludoch 

It would be better if it could be:
```
FROM gcr.io/google_appengine/openjdk8
ADD foo.jar /app/
ENTRYPOINT ["/docker-entrypoint.bash"]
CMD ["java","-jar","/app/foo.jar"]
```
As this would allow a docker-entrypoint.bash script similar to the one in gke-jetty to run and add the cdbg, alpn and cprof properties as needed.   It would also allow for docker commands like:
```shell
docker run theImage -verbose
```
to simply add JVM arguments
or commands like
```shell
docker run theImage bash
```
to explore the image.

I will write this entry-point now to better illustrate
