### ISSUE TITLE
appengine-java-vm-runtime - No longer builds using Java7

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#119]
Switch to Java7, do a `mvn clean`

`$ mvn install`
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Google App Engine Runtime Parent
[INFO] Google App Engine Logging Support
[INFO] Google App Engine Image for OpenJDK
[INFO] Google App Engine Image Jetty
[INFO] Google App Engine Runtime Support
[INFO] Compatibility test application
[INFO] Google App Engine Image for GAEv1 Java Compatibility
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google App Engine Runtime Parent 1.9.26-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ appengine-java-vm-runtime ---
[INFO] Installing /Users/lesv/github/appengine-java-vm-runtime/pom.xml to /Users/lesv/.m2/repository/com/google/appengine/appengine-java-vm-runtime/1.9.26-SNAPSHOT/appengine-java-vm-runtime-1.9.26-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google App Engine Logging Support 1.9.26-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ appengine-java-logging ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/lesv/github/appengine-java-vm-runtime/appengine-java-logging/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ appengine-java-logging ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/lesv/github/appengine-java-vm-runtime/appengine-java-logging/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google App Engine Runtime Parent ................... SUCCESS [  0.289 s]
[INFO] Google App Engine Logging Support .................. FAILURE [  0.595 s]
[INFO] Google App Engine Image for OpenJDK ................ SKIPPED
[INFO] Google App Engine Image Jetty ...................... SKIPPED
[INFO] Google App Engine Runtime Support .................. SKIPPED
[INFO] Compatibility test application ..................... SKIPPED
[INFO] Google App Engine Image for GAEv1 Java Compatibility SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.032 s
[INFO] Finished at: 2015-10-25T13:05:03-07:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project appengine-java-logging: Fatal error compiling: invalid target release: 1.8 -> [Help 1]**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :appengine-java-logging

**Comment by gregw** [comment]
@lesv This is by design.  Master branch has been switched to used openjdk8 and jetty 9.3 (which depends on openjdk 1.8).

**Comment by lesv** [comment]
Sounds good -- I just had some instructions that was referencing it as Java7.  I guess I can point them at the jetty-9.2 branch if I need that to stay working.
