### ISSUE TITLE
Replace  SaveSessionFilter

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/appengine-java-vm-runtime#121]
The SaveSessionFilter ensures that sessions whose attributes have been changed during a request are written through to the memcache and datastore services.

It would be possible to remove that filter and add code to the AppEngineSession and SessionManager that would invoke the save as the *last* request exits.  Other session managers implemented in the jetty code base already do this (see for example https://github.com/eclipse/jetty.project/blob/master/jetty-infinispan/src/main/java/org/eclipse/jetty/session/infinispan/InfinispanSessionManager.java#L371, https://github.com/eclipse/jetty.project/blob/master/jetty-nosql/src/main/java/org/eclipse/jetty/nosql/NoSqlSession.java#L139).

This might also be a good opportunity for jetty to cut down duplicate code in the AbstractSessionManager subclasses by pushing the request-counting code down into the AbstractSessionManager base class,  and then add a hook to allow subclasses to easily execute code when the request count == 0.

**Comment by gregw** [comment]
Note that I'm currently moving the save session functionality out of the filter into the onComplete listener in async branch.

This removes the filter, but is still a poor way of saving the session, so the count==0 approach may still be preferable - implemented in the session manager.

**Comment by gregw** [comment]
obseleted
