### ISSUE TITLE
async-branch build image failure

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#126]
I see 
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.2:build (build) on project gke-debian-openjdk: Exception caught: The command [/bin/sh -c echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list  && apt-get -q update  && apt-get -y -q --no-install-recommends install     ca-certificates     openjdk-8-jre     netbase     wget  && wget http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2d-1_amd64.deb          http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-1_amd64.deb  && dpkg -i openssl_1.0.2d-1_amd64.deb libssl1.0.0_1.0.2d-1_amd64.deb  && rm openssl_1.0.2d-1_amd64.deb libssl1.0.0_1.0.2d-1_amd64.deb  && apt-get clean  && rm /var/lib/apt/lists/*_*] returned a non-zero code: 8 -> [Help 1]

Is it because the same command installs wget and uses wget now to install openssl?

**Comment by ludoch** [comment]
nope....log just before the error:
.....
[91m....[0m
[91m..... ...[0m
[91m       100% 63.2M=0.3s

[0m
[91m2015-11-10 10:04:58 (4.71 MB/s) - 'libssl1.0.0_1.0.2d-1_amd64.deb' saved [1273692/1273692]

[0m
[91mconverted 'http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-1_amd64.deb' (ANSI_X3.4-1968) -> 'http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-1_amd64.deb' (UTF-8)
[0m
[91m--2015-11-10 10:04:58--  http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-1_amd64.deb
[0m
[91mReusing existing connection to ftp.us.debian.org:80.
[0m
[91mHTTP request sent, awaiting response... [0m
[91m404 Not Found
2015-11-10 10:04:58 ERROR 404: Not Found.

**Comment by ludoch** [comment]
error: openssl_1.0.2d-1_amd64.deb is not there anymore.
It is 
http://ftp.us.debian.org/debian/pool/main/o/openssl/openssl_1.0.2d-3_amd64.deb

Did it disappear?

**Comment by gregw** [comment]
I wonder if we should make this build more durable by mirroring such wget targets as a maven artefact.  Eg have a appengine-java-vm-runtime-dependencies module that publishes those debs as artefacts.     Thus once we do a release they will be published in a durable repository and our builds will not suddenly fail if debian changes their repo.

or is there a more durable location to fetch debs directly?

**Comment by gregw** [comment]
I'm closing this for now.  Will open a new issue if durability of debs becomes a problem
