### ISSUE TITLE
if the war file added to the jetty image is read only for the user only, Jetty cannot access it.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#127]
See generic Docker issue with file protections and Docker images:
https://github.com/docker/docker/issues/6119

The staging phase of the maven plugin could add r--r--r to the war, so that the Docker image is not bloated?
Or we remove the jetty user?

**Comment by gregw** [comment]
See https://github.com/docker/docker/issues/6119#issuecomment-46689247   which says docker recommends using non privileged users for services.

We should ensure that the war is readable by the jetty user.  Perhaps the add command will respect a g+s on the directory?     I will experiment...

**Comment by ludoch** [comment]
For now, I hacked something in the Maven plugin, but that would work only via Maven, not CLI or Gradle.

**Comment by gregw** [comment]
replaced by https://github.com/GoogleCloudPlatform/jetty-runtime/issues/11
