### ISSUE TITLE
support servlet renewSessionID

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#138]
Not sure what happened to this one, but it seems we did not fix it at all.

managed vm java runtime is missing the Servlet 3.1-HttpServletRequest.changeSessionID functionality. The reason for this seems to be missing implementations of the "renewSessionID"-methods in the appengine sessionmanager and sessionIdManager implementations.

I thought I tracked this bug here, but apparently not.

**Comment by janbartel** [comment]
@ludoch,  there was this pull request from me back in September IIRC: https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/70

**Comment by ludoch** [comment]
Good and sorry for the question. I was looking for a bug and could not find it without looking at the prs.
Marking as closed.
Thanks again for your detective work:-)
