### ISSUE TITLE
appengine-java-vm-runtime change debian

### ISSUE THREAD

**Issue by YunchaoGongSC** [GoogleCloudPlatform/appengine-java-vm-runtime#14]
I tried to install nacl and use nacl to compile other libraries based on the this image, and I have a problem finding the C compiler, and also run into many problems for other libraries. When I changed to debian:testing as the base image, everything works. So I am wondering can I directly use debian:testing as the base image of appengine-java-vm-runtime (instead of google/debian), and then deploy a VM instance? I tried so but it seems I have not be able to successfully deploy it yet. It will be great to get more information from you, thanks!

**Comment by ludoch** [comment]
yes, you can clone this repository and change the base image you need for the Dockerfile.
You then build your image, locally. You may push it to the Docker hub if you want.
Let's say you call your built image YunchaoGongSC/myimage

You can then use it as
FROM YunchaoGongSC/myimage
ADD . /app
