### ISSUE TITLE
Please rename folders to prevent confusion

### ISSUE THREAD

**Issue by arouzrokh** [GoogleCloudPlatform/appengine-java-vm-runtime#141]
gke-debian-openjdk -> openjdk8
gke-jetty-> jetty9

We will keep the version numbers as they are useful. 

README in each image directory should have full description of what versions of JDK or Jetty are included (major and minor version) even though this information can probably be discerned from the dockerfile. 

Thanks.

**Comment by gregw** [comment]
@ludoch I think we need a more thorough review of the naming conventions, specially with the work that I'm currently doing for #140 which adds additional modules and images.

Currently in my branch for #140 I have the modules below and propose the renaming as follows:

Module | Artefact | Comment | New Name?
----------|----------|-------------|-------
gke-debian-openjdk | image | debian/java image suitable for GKE | gke-debian-openjdk8
gke-jetty | image | jetty image suitable for GKE | gke-jetty9
appengine-java-logging | jar | JsonFormatter and LogContext for java.util.logging.   Should be merged into appengine-managed-runtime and thus avoid the "java" in the name? | -
appengine-managed-runtime | jar | Non container specific runtime classes. | managed-runtime
jetty-managed-runtime | jar + zip | Container specific runtime classes. Produces a zip of a $JETTY_BASE directory capable of running compat webapps.  | managed-runtime-jetty9??
gae-jetty-managed-runtime | image | Uses managed-runtime-jetty9 and gke-jetty9 to create compat docker image | gae-managed-runtime-jetty9

This uses the gke- prefix to identify modules that produce images that can be deployed on GKE and gae- for the GAE images.   Other modules just have functional names scoped by the package com.google.apphosting

I'll proceed on this basis in my #140 work, but happy to rename again if there is a better scheme.

**Comment by gregw** [comment]
Another complication is the docker image names themselves.   Currently gke-debian-openjdk produces a docker image of the same name with the label 8-jre, which matches the conventions for the standard docker images.

If we rename this module to gke-debian-openjdk8, then what should the label be?  Just "latest" or perhaps the specific version of openjdk8  eg u51 ?

**Comment by ludoch** [comment]
See a start  of a PR at
https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/146

**Comment by ludoch** [comment]
gcr,io names are there:
https://cloud.google.com/appengine/docs/managed-vms/custom-runtimes

**Comment by ludoch** [comment]
that would give these local image names

 docker images

REPOSITORY                          TAG                     IMAGE ID
    CREATED                  VIRTUAL SIZE

jetty9-compat                       async-1.9.30-SNAPSHOT   ba399c384bdc
    Less than a second ago   464.3 MB

jetty9-compat                       latest                  ba399c384bdc
    Less than a second ago   464.3 MB

jetty9                              async-9.3.5.v20151012   b5e6268572a4
    13 seconds ago           444.9 MB

openjdk8                            async-8-jre             17b4190669a9
    18 seconds ago           420 MB

<none>                              <none>                  e5184c885a56
    6 hours ago              464.3 MB

gcr.io/google_appengine_qa/debian   latest                  8f8068a6a6b4
    5 months ago             163.5 MB

**Comment by ludoch** [comment]
The merge can wait your other activities.

**Comment by gregw** [comment]
Fixed in async-support branch
