### ISSUE TITLE
libssl artifact no longer available

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#143]
The master build is currently failing as the libssl1.0.2_1.0.2d-3_amd64.deb is no longer available from 
http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.2_1.0.2d-3_amd64.deb

A libssl1.0.2_1.0.2e-1_amd64.deb is now available from that location, but we cannot be forced into upgrades like that. We either need to find a durable store for deb, or export one into the maven repo, so it become durable.

**Comment by joakime** [comment]
It seems that the original URL to libssl1.0.2d is for the sid (unstable) tree of Debian.
libssl1.0.2 is not present in in the packaging or indexes for debian stable, debian 8.2, or debian wheezy (those releases are all on libssl1.0.0)

libssl version 1.0.2 is also not present on `archive.debian.org`

libssl1.0.1k is part of jessie(stable) though

The requirement for libssl1.0.2 is actually going to change, frequently, until it enters into the stable trees.

Can you make this requirement multi-stage?

Technique 1:

 1. Get the index from http://ftp.us.debian.org/debian/indices/files/components/arch-amd64.list.gz
 2. Then use the regex `pool\/main\/o\/openssl\/libssl1\.0\.2.*amd64\.deb$` to get the last hit in that index.
 3. That last result is either what you fetch, or a build error?

Technique 2:

 1. Get https://packages.debian.org/sid/amd64/libssl1.0.2/download
 2. Use the link to http://ftp.us.debian.org/ as the "live" version

**Comment by joakime** [comment]
libssl 1.0.2 is also available on `stretch (testing)`

https://packages.debian.org/stretch/libssl1.0.2

**Comment by joakime** [comment]
Link to keep track of all libssl1.0.2 related packages (no matter what suite its found in) - https://packages.debian.org/search?keywords=libssl1.0.2

**Comment by joakime** [comment]
Completed as part of PR #177
