### ISSUE TITLE
review class hiding and see if jarjar renaming makes hiding simpler.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#149]
Related to the new jetty base zip creation https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/147

lib/gae/ jetty base will contained non jarjared classes, mostly:
```
httpcore-4.4.1.jar
commons-codec-1.10.jar
gson-2.3.1.jar
commons-logging-1.2.jar	
httpclient-4.4.1.jar
```
that should not be exposed to user applications at all.
I do not see guava there. is it coming from Jetty?

**Comment by ludoch** [comment]
Forget about my guava comment. We already are repackaging it in our appengine api.jar and this is what is used.

**Comment by gregw** [comment]
We also can consider the shade plugin as an alternative to jarjar

**Comment by janbartel** [comment]
@gregw is this related to #259?

**Comment by gregw** [comment]
Subsumed by #259
