### ISSUE TITLE
StubSession shouldn't throw RuntimeException

### ISSUE THREAD

**Issue by erugeri** [GoogleCloudPlatform/appengine-java-vm-runtime#15]
I have an App Engine sandbox application that doesn't use sessions (<sessions-enabled>false</sessions-enabled>). It works perfectly.

On Managed-VM, I get the following exception: 
```java.lang.RuntimeException: Session support is not enabled in appengine-web.xml.  To enable sessions, put <sessions-enabled>true</sessions-enabled> in that file.  Without it, getSession() is allowed, but manipulation of sessionattributes is not.```

thrown by https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/master/appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/StubSessionManager.java#L100

To make my app work on MVM, I'm forced to activate sessions, thus creating more load and more writes on the datastore. 
Strangely, the problem doesn't happen when I access through the appspot url. The session set or remove calls are probably generated by frameworks (using Jersey + JSP + JSTL) but the call success aren't necessary to the app.

Thanks

**Comment by erugeri** [comment]
As a workaround, and until a better solution is found, here's what we did in case anybody is interested:

- Created a queue named "sessions". And I paused it on the web admin interface so that no task is processed

- Added the following in the config xml:
 	<sessions-enabled>true</sessions-enabled>
	<async-session-persistence enabled="true" queue-name="sessions"/>

- Created a cron that is called every minute and does: QueueFactory.getQueue("sessions").purge();

Like that, we don't waste resources writing on the datastore (and we don't pay for useless writes/read/storage and deletes).
However we are still uselessly writing and reading from memcache so that's not good but it's still better :(

**Comment by ludoch** [comment]
looking into it.
We might not need at all the stubsessionmanager.

**Comment by erugeri** [comment]
FYI, the problem still seems present in app engine 1.9.30.
