### ISSUE TITLE
Enable logging in jetty9 docker image

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#158]
This will need to use the appengine-java-logging artefact

**Comment by gregw** [comment]
@ludoch Do you want request logging; server logging; or both enabled in the jetty9 image?

**Comment by gregw** [comment]
@ludoch if it is to be server logging as well, then should I rename appengine-java-logging to mvm-java-logging?

**Comment by ludoch** [comment]
Both would be nice. Let's not rename for now, naming is in flux....

Ludo
