### ISSUE TITLE
ImagesService isn't available on ManagedVM

### ISSUE THREAD

**Issue by erugeri** [GoogleCloudPlatform/appengine-java-vm-runtime#16]
When trying to call ImagesServices from a managed VM runtime, I get:

```
com.google.apphosting.api.ApiProxy$FeatureNotEnabledException: This feature is disabled for Managed VMs.
```

What is the recommended workaround?

**Comment by ludoch** [comment]
Hi,
There are many open source Java alternatives, that did not work in GAE V1
but that are fully functional on Managed VMs for image processing.

**Comment by erugeri** [comment]
Thanks for the quick reply. 
I'll try to find a lib that suits our needs. If you have any recommendations it'd be great ;)

**Comment by erugeri** [comment]
For those interested, I found a great lib: http://www.thebuzzmedia.com/software/imgscalr-java-image-scaling-library/

maven dependency:
```
	<dependency>
		<groupId>org.imgscalr</groupId>
		<artifactId>imgscalr-lib</artifactId>
		<version>4.2</version>
	</dependency>
```

usage:
```
	BufferedImage resizedImage = Scalr.resize(originalImage, 
					Scalr.Method.AUTOMATIC, 
					Scalr.Mode.AUTOMATIC,
	                maxWidth, maxHeight);
```

**Comment by ludoch** [comment]
Thanks for the info, it will be useful for other folks.
Closing this one now.
