### ISSUE TITLE
Compat runtime needs to log GAE API calls

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#166]
new product requirement:
the Java compat runtime should log all API calls made over the service bridge at INFO level with the following information:

- The service being called
- The API method (from headers)
- The HTTP status code for the reply
- The latency of the reply (or none if a timeout)
- The RPC code for the reply if possible (this may have to be fetched from the contents of the reply which may make it technically difficult)
- The request and response size

**Comment by gregw** [comment]
@joakime can you take this one to get you in the game!    I think the logging can be done [here](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/master/appengine-managed-runtime/src/main/java/com/google/apphosting/vmruntime/VmApiProxyDelegate.java#L152)

**Comment by ludoch** [comment]
Fix looks good! Thanks.
