### ISSUE TITLE
jdk7u95 may need a new alpn-boot

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#169]
@ludoch - Probably not the right venue, but I'm not sure how to write bugs against the jetty project.

jdk7u95 has been pushed to wheezy -- it appears to not work w/ 7.1.3 of alpn-boot

**Comment by ludoch** [comment]
Lesv, you should move this bug under the Jetty Eclipse bug system.

**Comment by joakime** [comment]
going to be hard to validate this updated alpn-boot jar, as 7u95 is only available to "My Oracle Support" contract people.

**Comment by joakime** [comment]
the openjdk at least has a tag for it.  got that going for us at least.

http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/tags
http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/3a74fee9ba00

**Comment by joakime** [comment]
Looks like Fedora 20 (but not versions of Fedora after 20) has access to openjdk 7u79 via the apt packaging system.

The Ubuntu precise (12.04LTS) thru wily (15.10) releases also have access to openjdk 7u79 available in their yum packaging system.

**Comment by gregw** [comment]
closed due to #280
