### ISSUE TITLE
Request never completing - JSP infinite loop

### ISSUE THREAD

**Issue by erugeri** [GoogleCloudPlatform/appengine-java-vm-runtime#17]
When I stop a MVM version. I can see multiple queries being stopped (Error 500). Theses queries were running indefinitely for a few hours and never finished.

They are for a quite heavy JSP page, the HTML is around 7 mo. I added logs and the problem seems to be in the JSP processing or after. 
The page loads in less than 5 seconds 95% of the time. But for around 5% of requests, it will never load and hangs indefinitely doing probably nothing.

The page is working perfectly when in the 'sandbox' environment.

**Comment by ludoch** [comment]
Can we easily reproduce it with a large JSP? If you can share some code, that would be great.

**Comment by erugeri** [comment]
I tried to reproduce it but wasn't able to. It seems the issue has been fixed!
Last time I remember seing it was 2 or 3 weeks ago.
Since, we moved our frontends to n1-standard-2 instances, maybe it's linked?

I let you close the issue if you want to. I'll reopen it if I see it again in the future.

Thanks!

**Comment by ludoch** [comment]
closing now.
