### ISSUE TITLE
Question - MVM and MemCache Access in the new MVM Feb 2016 Release 

### ISSUE THREAD

**Issue by suttiwat** [GoogleCloudPlatform/appengine-java-vm-runtime#170]
Hi 

I've seen new document talking about MVM and MemCache access in new way .  https://cloud.google.com/appengine/docs/managed-vms/java/caching-application-data

I'm using MVM since year 2015.  The way I access MemCache it still be the same with AppEngine  (https://cloud.google.com/appengine/docs/java/memcache/)  Accessing by  MemcacheService syncCache = MemcacheServiceFactory.getMemcacheService();
  

So my question is  Do I need to change my code to new way (https://cloud.google.com/appengine/docs/managed-vms/java/caching-application-data) or not ??  please suggest. 

Thanks.

**Comment by ludoch** [comment]
If you use the compat runtime described in the docs, the GAE standard APIs are supported, including the memcache apis you are currently using.

The new APIs are for accessing Cloud services from anywhere, including Managed VMs, GKE, your laptop, etc...
