### ISSUE TITLE
All MVM instances restart at the same time

### ISSUE THREAD

**Issue by erugeri** [GoogleCloudPlatform/appengine-java-vm-runtime#181]
Hi,

It's been the second time this week (last time was around 10:30 AM GMT on Feb 18th, and now is 09:16 AM GMT on Feb 21st) that suddenly our servers ALL shutdown without any reason. We have 2 modules (one default and one backend), each with 3 instances. All 6 instances were suddenly off.
![frontend]
(http://i.imgur.com/VeC2ool.png)

All requests were 500 with the following error message: Request attempted to contact a stopped backend.
![Error msg]
(http://i.imgur.com/zKUGoAv.png)

Around 6-7 minutes of downtime later, the situation resolved itself. As you can see the instances are supposed to be started Feb 19th, 15:24, however they were just restarded a few minutes before (number of request should have been in the millions otherwise).
![Resolution]
(http://i.imgur.com/hYzcs5u.png)

At the same time we redeployed a default frontend version so I don't now if the restarted frontends would have worked well. However the restarted backends were not good and all were sending:
```
com.google.apphosting.api.ApiProxy$ArgumentException: An error occurred parsing (locally or remotely) the arguments to DATASTORE_V3.Put().
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertApiResponseRpcErrorToException(VmApiProxyDelegate.java:399)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertRemoteError(VmApiProxyDelegate.java:343)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.runSyncCall(VmApiProxyDelegate.java:187)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeApiCall(VmApiProxyDelegate.java:154)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.access$000(VmApiProxyDelegate.java:60)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate$MakeSyncCall.call(VmApiProxyDelegate.java:436)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate$MakeSyncCall.call(VmApiProxyDelegate.java:412)
```

Thanks for your concern,

**Comment by erugeri** [comment]
Issue happened again right now :(
Would really appreciate if that new infrastructure problem is acknowledged.

**Comment by erugeri** [comment]
We think it's a load balancer issue this time as we can contact the instances by their id:
http://0.version.module.adbuddiz-prd.appspot.com/ or 1 or 2.
but http://version.module.adbuddiz-prd.appspot.com/ doesn't work.

**Comment by ludoch** [comment]
I will file an internal bug... Did you contact support?

**Comment by erugeri** [comment]
Thanks @ludoch. I didn't contact support, when I did in the past I didn't find it really helpful to be honest as MVM is still in Beta. Here's the kind of reply I got at the time:

"I would highly recommend you to use App Engine's standard runtime if possible, as it is reliable and stable, instead of a custom runtime within a Managed VM."

"At this time, I would like to reiterate that ManagedVMs are still in BETA and are not suitable for systems that need to be relied upon".

By the way, do you have any idea when beta will end?

**Comment by lesv** [comment]
Support should actually help you in these cases.  If not, mention it here and we will get the right person to you.  Support can do some fairly amazing things that are outside of my ability for things like this.  They also gave us a way to help in the future, but really this kind of things should go to them.

**Comment by ludoch** [comment]
Yes, keep notifying support, this is the way to get all the feedback we
need before we can move off alpha or beta.
