### ISSUE TITLE
mvn jetty:run - w/ web.xml ignores annotation...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/appengine-java-vm-runtime#185]
I'm still making sure I don't have a pilot error, but it appears that if I add a webapp/WEB-INF/web.xml then my annotations are no longer processed.

I think I understand this as @ludoch does a bunch of stuff in the gcloud-plugin, it's not a great experience for users.

**Comment by ludoch** [comment]
Gae annotations processing is only for gcloud:run , jetty:run does not need
it as you specify app.yaml content yourself.

**Comment by ludoch** [comment]
And jetty:run ought to understand both annotations and a web.XML.
I guess you have a user error;)

**Comment by lesv** [comment]
It's possible I made an error, but I don't think so.
1. Two Servlets Hello path=/hello, Dump path=/dump using annotations
2. mvn clean jetty:run
3. Access localhost:8080 -> file display, localhost:8080/hello - Works, localhost:8080/dump -> lots of content.
4. add web.xml, <web-app><welcome-file-list><welcome-file>/hello</welcome-file></welcome-file-list></web-app>
5. mvn clean jetty:run
6. localhost:8080/hello -> Not Found, localhost:8080/demo -> not found, localhost:8080/ -> not found

I know I've seen this work in the past, so I agree, it's likely user error, but odd.

Jetty-plugin 9.3.7.v20160115

**Comment by lesv** [comment]
k - it's me.  I was getting used to maven's allowing abbreviated XML. (w/o namespace specifier)

When I put the namespace back in, things worked.
