### ISSUE TITLE
Session content not persisted to datastore with Managed VMs

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#186]
See https://code.google.com/p/googleappengine/issues/detail?id=12766

Maybe some configuration issue?

**Comment by gregw** [comment]
Actually we may not have actually tested to writing of the attributes!   It may be that we are no longer flushing the attributes as the session commit code has been changed in the async branch.

**Comment by gregw** [comment]
I've just run a test with a 4 instance version of the guest book, an the [dump servlet](http://20160301t095731-dot-jetty9-work.appspot.com/dump/info) (use query params to set session attributes that take affect after dump),  indicates that session values are being shared between instances.

**Comment by mdelem** [comment]
May I ask which version of the guestbook are you using?
This one is java7: https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras/blob/master/stage1/pom.xml
This one is java8: https://github.com/GoogleCloudPlatform/appengine-java-vm-guestbook-extras/blob/master/stage3/pom.xml

In the case of my application the dump servlet works for java7 but fails for java8 (reported as a "custom" runtime in the Cloud Console).

java7 => Session is successfully created, read and written
custom (java8) => Session is successfully created and read (for example it reads the attributes written with the java7 runtime) BUT it is not written

This is not specifically a multi-instance issue. I observe the bug on a single instance.

**Comment by gregw** [comment]
@mdelem I used stage3 and java8 and was able to see session values being saved.

Can you perhaps build a little maven project with a dump servlet that can be deployed with `mvn gcloud:deploy` so I can test it?

**Comment by mdelem** [comment]
Yep sure. So I've removed everything except the dump servlet from my project and created two versions: one with java7 and one for java8.

https://drive.google.com/folderview?id=0B6TJ2W_M9IK9UWMwSXA1ZXNObjA&usp=sharing

After you've deployed it the dump servlet is available at /_ah/dump

For me the java7 version works as intended but the java8 doesn't. The only change between the two projects are the lines in the pom.xml that specify the compilation target.

**Comment by ludoch** [comment]
Hi Greg,
Maybe there is a difference there between the default java8 image and the
async branch image (not yet pushed as the default one)?

**Comment by janbartel** [comment]
I have been able to reproduce the error reported by @mdelem :  when the sample webapp is deployed to a java7 environment the session attributes are read and written, however when deployed to java8 (master) the session attributes do not appear to be written.  I surmise that perhaps the SessionSaveFilter has not been configured correctly in master, but am having trouble making progress on that because I can't get logging to work:  the LogViewer shows "FileNotFound: WEB-INF/logging.properties".

**Comment by ludoch** [comment]
Thanks Jane...
The log issue is fixed in the async branch only...

Next step would be to also test this branch...

**Comment by gregw** [comment]
This might explain why master has been so much faster that async as per #201.  It means that master has not been running lots of the filters!

However, I still would not think that it should slow the server down that much.  I will retest once this is merge.

**Comment by ludoch** [comment]
Greg: Good thinking... You can now retest, image push is happening.
