### ISSUE TITLE
app engine (java managed vm) async servlet support

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#187]
Need to investigate more:
https://code.google.com/p/googleappengine/issues/detail?id=12767
Maybe more samples or documentation needed.

**Comment by gregw** [comment]
I commented asking for details of the web.xml as it is a frequent mistake for applications to not mark their own filters as async-supported.

I better error from Jetty saying what component doesn't support async would be helpful, but hard to add until 9.4.x

**Comment by gregw** [comment]
I've added a [fix](https://github.com/eclipse/jetty.project/issues/379) that may be in 9.3.8 (if not then 9.3.9) that reports the source of the async not supported - ie which servlet/filter

**Comment by gregw** [comment]
Closed for now.  If further info becomes available, then a new issue should be opened on https://github.com/GoogleCloudPlatform/jetty-gae-compat-runtime
