### ISSUE TITLE
Add an e2e test using the test web app, using a real deployment and call some/most of the servlets in an automated fashion

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#195]
The Dockerfile used by the App should be using the latest image built locally (that would mean a local docker build), or we would need to push a snapshot of the image in gcr.io

**Comment by ludoch** [comment]
We could also deploy most of  the samples we have on github, again, using the latest snapshot image.

**Comment by ludoch** [comment]
Steps:
1/ find good web apps to deploy (including the test app we have in this repo)
2/ find the urls we want to activate
3/ configure the Dockerfile to use a latest image built (will need to cover the 3 images java8, jetty9, compat)
4/ call mvn gcloud:deploy with the correct appid and appversion
5/ execute the urls access
6/ produce a dashboard so we can keep tests results (at least keep the logs on a gcs bucket?)
7/ host this on a Jenkins instance? We have one internally I could configure.
8/ anything else or better?

**Comment by rdcastro** [comment]
For 1, you can consider sample apps that we have for Managed VMs @JustinBeckwith might be able to point you to some apps. For compat, it might be good to have apps that exercise all/mostly used APIs.

**Comment by JustinBeckwith** [comment]
Anything here should work :) 

https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/managed_vms

**Comment by gregw** [comment]
obsoleted by https://github.com/GoogleCloudPlatform/jetty-runtime/issues/8
