### ISSUE TITLE
Compare head and async branch regarding workload

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#201]
We did some informal load test of a web app using GAE APIs and it seems the async-branch delivers lower QPS than head...
It might be due to either the async work done, or the global API ticket usage.

I will provide the test web app (it will be in Open Source soon) and the way to run the load test.
We need to reproduce and analyse the diff with different configurations.
We can then start a regular perf end2end test that we could run nightly on our Jenkins far to track possible regressions early in the dev cycle.

**Comment by gregw** [comment]
first quick look at benchmark tool indicates that it is trying to measure the right thing.    Tools that report "achieved" throughput are rarely actually measuring throughput.   This tool is correctly offering load in increments and charting the achieved latencies at 90% 95% and 99% to see if an acceptable QoS is achieved.       So that is good.... now have to look into why async branch is doing badly.

**Comment by gregw** [comment]
OK, I take it back about the wrk benchmark tool.  The load it offers is a function of observed latency, so it's throughput numbers are actually measuring latency rather than throughput.  

However, having said that, I'm seeing 100ms more latency on the async branch than from master, even on a non-authenticated path that should do no API calls.    That is a long time, so I need to work out how to work out what is going on.....  stand by...

**Comment by gregw** [comment]
progress report.... I've been deploying instrumented versions of the async image and there is an unusual latency spent between dispatching the request and entering the context, which suggest the session manager.    I will zero in a bit more today.

**Comment by gregw** [comment]
History logged on [instrumented image](https://20160322t120513-dot-jetty9-work.appspot.com/dump/) definitely indicates that a lot of time is spent in session manager doScope:
````
92361917790408, 92361917790408,Endpoint Opened
    54280, 92361917844688,Last Selected
   180932, 92361918025620,RequestContext created
    41280, 92361918066900,VmApiProxyEnv created
     3643, 92361918070543,enterScope
     4504, 92361918075047,session.doScope
 20541498, 92361938616545,servlet.doScope
    23490, 92361938640035,requestInitialized
     7655, 92361938647690,session.doHandle
     1728, 92361938649418,security.handle
    62764, 92361938712182,servlet.doHandle
    16212, 92361938728394,doGet
   591225, 92361939319619,response written
   188396, 92361939508015,flushed
````

**Comment by gregw** [comment]
A bit more instrumentation shows that the vast majority of the time is spent loading the session:
````
367386447442, 367386447442,Endpoint Opened
   227368, 367386674810,Last Selected
   411464, 367387086274,RequestContext created
   116828, 367387203102,VmApiProxyEnv created
     6082, 367387209184,enterScope
    14881, 367387224065,session.doScope
    97107, 367387321172,getSession
    17976, 367387339148,loadSession
  4823773, 367392162921,loaded
    20561, 367392183482,gotSession
    22479, 367392205961,access
    12578, 367392218539,accessed
    12775, 367392231314,servlet.doScope
    34939, 367392266253,requestInitialized
    19310, 367392285563,session.doHandle
     5656, 367392291219,security.handle
   419231, 367392710450,servlet.doHandle
    36234, 367392746684,doGet
   599899, 367393346583,response written
  1246486, 367394593069,flushed
````

Now this may or may not be the same for the master branch, so that is next thing to check.

**Comment by ludoch** [comment]
So session handling is a possible candidate. It uses 2 big GAE APIs: datastore and memcache.
These API calls use the new global API ticket in async branch, which we need to see if this is the root cause. I suggest we build a patched head image only using global api ticket for all API calls and run the workload there to see if this would be a slow down issue from the environment outside of the JVM.

If yes, it's Flex framework bug, it not, then we need to compare all changes that happened in session management in the async branch?

**Comment by ludoch** [comment]
Any recent update?

**Comment by gregw** [comment]
Sorry,  no progress as easter is a long holiday in Australia. It is my top priority this week.

**Comment by gregw** [comment]
OK, some initial results with master updated to use the global ticket.     For low level load, the [asyncGlobalTicket](http://20160329t133429-dot-jetty9-work.appspot.com/dump/relax/info) version is slightly (and statistically not relevant) faster than the [masterGlobalTicket](http://20160329t124205-dot-jetty9-work.appspot.com/dump/relax/info) branch.

Results from running simultaneous wrt tests on low load are

masterGlobalTicket:
````
gregw@gcloud: ~/src/wrk (master)
[121] ./wrk -t 20 -c 100 -d 300s --latency http://20160329t124205-dot-jetty9-work.appspot.com/dump/relax/info
Running 5m test @ http://20160329t124205-dot-jetty9-work.appspot.com/dump/relax/info
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   263.94ms   97.39ms   1.51s    91.02%
    Req/Sec    20.28      9.82    50.00     58.34%
  Latency Distribution
     50%  245.98ms
     75%  287.99ms
     90%  338.62ms
     99%  633.17ms
  115150 requests in 5.00m, 0.94GB read
  Socket errors: connect 0, read 0, write 0, timeout 12
  Non-2xx or 3xx responses: 1
Requests/sec:    383.71
Transfer/sec:      3.20MB
````

asyncGlobalTicket:
````
gregw@gcloud: ~/src/wrk (master)
[112] ./wrk -t 20 -c 100 -d 300s --latency http://20160329t133429-dot-jetty9-work.appspot.com/dump/relax/info
Running 5m test @ http://20160329t133429-dot-jetty9-work.appspot.com/dump/relax/info
  20 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   257.94ms   68.78ms   1.69s    81.39%
    Req/Sec    20.20      9.27    50.00     40.41%
  Latency Distribution
     50%  244.60ms
     75%  283.17ms
     90%  331.72ms
     99%  517.85ms
  116624 requests in 5.00m, 0.96GB read
  Socket errors: connect 0, read 0, write 0, timeout 5
Requests/sec:    388.62
Transfer/sec:      3.29MB
````

I will now continue testing with higher loads and longer runs

**Comment by gregw** [comment]
I've been having trouble scaling this much more than 100 connections.  Both master and async start returning errors above that rate.

I also believe I have hit some usage limits for my account (I've been using the cloud shell as the client to generate load, so not sure if that is a client or a server limit I have hit).

In all testing, both master and async with global ticket appear to have similar performance - albeit at a much lower level than I would have expected.

**Comment by gregw** [comment]
@ludoch 
I'm working on the VmApiProxyEnvironment and it now contains both the request ticket and the globalticket.     The trick now is that once the response is committed, the request ticket is no longer valid, so I've got to invalidate the per request ticket so the global ticket will be used after that.    Not sure if it is best to test isCommitted each time or to install an output interceptor to intercept the commit...    run out of time today, but will pick an approach tomorrow.

**Comment by ludoch** [comment]
We also need the base numbers for the current default image using exclusively the request ticket.
Because I see with Globalticket, we have around 380QPS... But our internal benchmark was not seen the same number: the Async branch was measured at 128QPS...
Why are we seeing now 380QPS? Or maybe the internal measure is wrong. If we cannot reproduce it, I would be happy!

To recap:
image:                                                                  QPS
request ticket, no async branch image:                ?
global ticket, no async branch image:                  383
global ticket, no async branch image:                  388   (or 128???)

**Comment by gregw** [comment]
I've now got [4 images to test](https://console.cloud.google.com/kubernetes/images/tags/jetty9-compat?location=GLOBAL&project=jetty9-work&authuser=1) including async-support enhance to use the request ticket when possible (pull request coming soon).   Now working on a better benchmark webapp to test them against

**Comment by gregw** [comment]
I'm deploying the benchmark webapp that you sent me.... but I've not yet worked out how exactly to run a test client against it:

- [master](https://20160401t164624-dot-jetty9-work.appspot.com/)
- masterGlobalTicket
- async-support
- async-support-issue-201

**Comment by gregw** [comment]
I couldn't work out how to make a client work with the provided benchmark webapp, so I have just added my own DumpServlet to them all again.

Here is a typical trace for master branch:
````
[111] ./wrk -t 100 -c 100 -d 60s --latency --timeout 5s https://20160405t153712-dot-jetty9-work.appspot.com/dump
Running 1m test @ https://20160405t153712-dot-jetty9-work.appspot.com/dump
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   220.50ms   52.09ms   1.27s    88.36%
    Req/Sec     4.76      1.48    10.00     72.20%
  Latency Distribution
     50%  211.97ms
     75%  236.24ms
     90%  267.34ms
     99%  345.42ms
  27374 requests in 1.00m, 230.27MB read
Requests/sec:    455.48
Transfer/sec:      3.83MB
````
Looking at the trace of a minimal request (57ms) I can see that it spends 7ms in Jetty, 49ms saving the session to Datastore v3 an 1ms in memcache.


Master changed to just use the global ticket gives slower results like:
````
[112] ./wrk -t 100 -c 100 -d 60s --latency --timeout 5s https://20160401t231023-dot-jetty9-work.appspot.com/dump
Running 1m test @ https://20160401t231023-dot-jetty9-work.appspot.com/dump
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   279.28ms  135.18ms   3.33s    96.96%
    Req/Sec     3.76      1.19    10.00     57.16%
  Latency Distribution
     50%  262.11ms
     75%  286.66ms
     90%  317.73ms
     99%  956.00ms
  22255 requests in 1.00m, 187.21MB read
Requests/sec:    370.31
Transfer/sec:      3.12MB
````
The minimal trace I see is about  76ms.... but it is not broken down to operations, because without the request based ticket, the console is unable to associate the calls with the request!  Good reason for not using Global ticket if we can avoid it.... other than the fact that it is demonstrably slower!

... more analysis coming....

**Comment by gregw** [comment]
Doing the same tests on async-support  with and without global ticket....   first discovery is that performance is AWFUL!  Much worse than I was getting last week.

Good news is that not using the global ticket does improve performance by about the expected margin.  Here is async-support with global ticket:
````
[113] ./wrk -t 100 -c 100 -d 60s --latency --timeout 5s https://20160405t172701-dot-jetty9-work.appspot.com/dump
Running 1m test @ https://20160405t172701-dot-jetty9-work.appspot.com/dump
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   660.21ms  254.50ms   3.72s    89.90%
    Req/Sec     1.23      0.53     5.00     71.73%
Running 1m test @ https://20160405t172701-dot-jetty9-work.appspot.com/dump
  Latency Distribution
     50%  621.68ms
     75%  731.65ms
     90%  851.49ms
     99%    1.67s 
  9242 requests in 1.00m, 78.25MB read
  Socket errors: connect 0, read 2, write 0, timeout 0
Requests/sec:    153.78
Transfer/sec:      1.30MB
````
Again, because the global ticket was used, no detailed trace info is available.

Using the request ticket where possible we get:
````
[113] ./wrk -t 100 -c 100 -d 60s --latency --timeout 5s https://20160401t174613-dot-jetty9-work.appspot.com/dump
Running 1m test @ https://20160401t174613-dot-jetty9-work.appspot.com/dump
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   537.46ms  237.73ms   3.72s    91.27%
    Req/Sec     1.70      0.68     5.00     56.53%
  Latency Distribution
     50%  486.11ms
     75%  573.81ms
     90%  700.68ms
     99%    1.59s 
  11499 requests in 1.00m, 97.35MB read
Requests/sec:    191.33
Transfer/sec:      1.62MB
````
Better, but still half of master.       We can now see in the trace the datastorev3.Put(54ms) and Memcache.set(1ms), taking a reasonable amount of time, but the overall time in jetty is typically over 150ms!!

Now note that we are lucky we saw the trace, because this test is obviously not sending the session cookie so every request creates a new session which is saved.    Saving a session is done after request processing, which is often after the response is committed and we would switch back to the global ticket.   In this case the response is obviously buffered, so we can see the trace.       But for the purposes of trace, it would be good if we could uses the request ticket after the response is committed.  Perhaps we need a feature request? or at least clarification of exactly when it becomes unavailable.

The other interesting thing is that the datastore.Put kicks off at 6ms, which is the same for the master branch.  All the delay is split between the peroid between the return of the datastore Put and the memcache set, then after the memecache set?     This is a strange place for the delay to be and I can't think what the server might be doing there.  It also was not reflected in my earlier tests, which saw < 10ms of latency within that part of the code?

So I'm not making much progress sorry.   It would be good if I could get the documentation on the test webapp shared so I can understand how to build a client to test it.    I also do not believe that wrk is a reasonable test client if it is not able to simulate requests over the same session.

But even with these limitations, there is something going on with the async-support branch deployments that is a) highly variable from day to day; b) difficult to understand;  c) difficult to observe.
So lots of work to do here!

**Comment by ludoch** [comment]
updated head image is there.
Would be nice to do a run with sessions disabled in the appengine-web.xml to see the impact of session management.

**Comment by gregw** [comment]
I have rerun some tests against master patched for #186 and have achieved the results below.   So while this has slowed down master a little, there is still a missing 200ms or so we are chasing.

````
gregw@gcloud: ~/src/wrk (master)
[115] ./wrk -t 100 -c 100 -d 60s --latency https://20160412t095844-dot-jetty9-work.appspot.com/dump
Running 1m test @ https://20160412t095844-dot-jetty9-work.appspot.com/dump
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   256.53ms   50.46ms   1.02s    76.00%
    Req/Sec     3.95      1.15    10.00     93.61%
  Latency Distribution
     50%  247.39ms
     75%  278.51ms
     90%  319.53ms
     99%  414.34ms
  23401 requests in 1.00m, 196.74MB read
Requests/sec:    389.37
Transfer/sec:      3.27MB
````

So this week I will produce a fully instrumented async-support image that will tell me exactly where all the time is being spent on these requests.

**Comment by gregw** [comment]
I've inverted my approach to this performance issue and have found some more strangeness.    I started by running the test against local versions of pure jetty  9.3.5(as used by master) and 9.3.8 (as used by async) and they basically come out the same:
````
gregw@Tile440: ~/src/gcloud/wrk (master)
[2149] wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://localhost:8080/dump/info/9.3.5
Running 5m test @ http://localhost:8080/dump/info/9.3.5
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    42.40ms   62.18ms 660.05ms   86.07%
    Req/Sec    68.22     76.37     2.03k    90.54%
  Latency Distribution
     50%   16.30ms
     75%   58.12ms
     90%  130.54ms
     99%  270.11ms
  1776311 requests in 5.00m, 12.53GB read
Requests/sec:   5919.10
Transfer/sec:     42.76MB

gregw@Tile440: ~/src/gcloud/wrk (master)
[2019] wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://localhost:8080/dump/info/9.3.8
Running 5m test @ http://localhost:8080/dump/info/9.3.8
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    42.25ms   61.53ms 865.18ms   85.89%
    Req/Sec    68.05     79.55     2.00k    90.32%
  Latency Distribution
     50%   16.09ms
     75%   58.62ms
     90%  129.89ms
     99%  265.38ms
  1770302 requests in 5.00m, 12.49GB read
Requests/sec:   5899.07
Transfer/sec:     42.62MB
````

But if I `mvn gcloud:deploy` the same webapp to the pure jetty images generated by master (with no compat) I get significantly different performance, with the 9.3.8 image being a lot slower:
````
gregw@gcloud: ~/src/wrk (master)
[139] ./wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t125925-dot-jetty9-work.appspot.com/dump/info/9.3.5
Running 5m test @ http://20160425t125925-dot-jetty9-work.appspot.com/dump/info/9.3.5
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   143.24ms   58.43ms   1.30s    94.53%
    Req/Sec     8.05      2.50    10.00     62.06%
  Latency Distribution
     50%  131.69ms
     75%  150.75ms
     90%  177.20ms
     99%  274.41ms
  213472 requests in 5.00m, 1.32GB read
Requests/sec:    711.33
Transfer/sec:      4.51MB
gregw@gcloud: ~/src/wrk (master)
[140] ./wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t124559-dot-jetty9-work.appspot.com/dump/info/9.3.8
Running 5m test @ http://20160425t124559-dot-jetty9-work.appspot.com/dump/info/9.3.8
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   169.43ms   62.32ms   1.42s    92.35%
    Req/Sec     6.88      2.63    10.00     51.91%
  Latency Distribution
     50%  156.98ms
     75%  184.10ms
     90%  219.91ms
     99%  353.18ms
  179532 requests in 5.00m, 1.16GB read
Requests/sec:    598.24
Transfer/sec:      3.96MB
````

The main difference I can see between these two images, other than jetty is that they are based on different debians: master is based on `gcr.io/google_appengine_qa/debian` while async is based on `gcr.io/google_appengine/base`

Could that be sufficient to cause such a performance difference?

**Comment by gregw** [comment]
I tried 4 cores, just to make sure it was not a single threaded issue in 9.3.8 and there is still a performance difference:
````
[145] ./wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t160327-dot-jetty9-work.appspot.com/dump/info/9.3.5-4core
Running 5m test @ http://20160425t160327-dot-jetty9-work.appspot.com/dump/info/9.3.5-4core
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   124.40ms   36.79ms   1.20s    93.17%
    Req/Sec     8.95      2.13    10.00     80.35%
  Latency Distribution
     50%  112.31ms
     75%  122.76ms
     90%  146.31ms
     99%  317.69ms
  244567 requests in 5.00m, 1.52GB read
Requests/sec:    814.95
Transfer/sec:      5.19MB
gregw@gcloud: ~/src/wrk (master)
[146] ./wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t161451-dot-jetty9-work.appspot.com/dump/info/9.3.8-4core
Running 5m test @ http://20160425t161451-dot-jetty9-work.appspot.com/dump/info/9.3.8-4core
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   136.63ms   49.61ms   1.31s    92.43%
    Req/Sec     8.43      2.44    10.00     70.50%
  Latency Distribution
     50%  121.57ms
     75%  140.30ms
     90%  172.10ms
     99%  363.59ms
  223791 requests in 5.00m, 1.45GB read
Requests/sec:    745.72
Transfer/sec:      4.95MB
````

**Comment by gregw** [comment]
I've build a jetty 9.3.8 image with the same qa base image that is used by master and it now achieves the same kind of throughput as 9.3.5-4core, or at least a lot closer.  I was getting 795 Requests/sec before I got disconnected from the cloud shell for excess network usage :(

**Comment by ludoch** [comment]
More data about the base images:
- gcr.io/google_appengine_qa/debian is the same as  gcr.io/google_appengine/debian
- gcr.io/google_appengine/base is built via this Dockerfile:

> FROM gcr.io/google_appengine/debian
>CMD []
>ENV DEBIAN_FRONTEND noninteractive
>ENV PORT 8080
>RUN apt-get -q update && \
    apt-get install --no-install-recommends -y -q ca-certificates && \
    apt-get -y -q upgrade && \
    rm /var/lib/apt/lists/*_*


So basically the same but some upgrade and installation of ca-certificates...
Weird...

**Comment by ludoch** [comment]
But the, the master base dockerfile for openjdk8 is:

https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/master/gke-debian-openjdk/src/main/docker/Dockerfile
>FROM gcr.io/google_appengine_qa/debian
>ENV DEBIAN_FRONTEND noninteractive
>RUN echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list \
 && apt-get -q update \
 && apt-get -y -q --no-install-recommends install \
    ca-certificates \
    openjdk-8-jre \
    netbase \
    wget \ 
    unzip \
 && apt-get clean \
 && rm /var/lib/apt/lists/*_*

where we also do an update (no upgrade) and ca-certificates installation with a modified sources.list

**Comment by gregw** [comment]
@aozarov @ludoch 
the pushed docker images I have been testing are:
 - gcr.io/jetty9-work/jetty9:9.3.5 : the gke-jetty:9.3.5.v20151012 image built from master branch
 - gcr.io/jetty9-work/jetty9:9.3.8 : the jetty9:async-9.3.8.v20160314 image built from async-support branch
 - gcr.io/jetty9-work/jetty9:9.3.8-qa : the jetty9:async-9.3.8.v20160314 image built from async-support branch patched to use the qa image (see below)


The currently running version are as follows (URI describes the image/instance used):
 - http://20160427t152506-dot-jetty9-work.appspot.com/dump/info/9.3.8-qa-4core
 - http://20160425t161451-dot-jetty9-work.appspot.com/dump/info/9.3.8-4core
 - http://20160425t160327-dot-jetty9-work.appspot.com/dump/info/9.3.5-4core
 - http://20160425t125925-dot-jetty9-work.appspot.com/dump/info/9.3.5
 - http://20160425t124559-dot-jetty9-work.appspot.com/dump/info/9.3.8

If you wanted to do a quick test, it would be good to know if you see any difference between 9.3.8-qa-4core and 9.3.8-4core, as the only difference between those is this patch:

````patch
diff --git a/openjdk8/src/main/docker/Dockerfile b/openjdk8/src/main/docker/Dockerfile
index 3dd7274..09aa53d 100644
--- a/openjdk8/src/main/docker/Dockerfile
+++ b/openjdk8/src/main/docker/Dockerfile
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM gcr.io/google_appengine/base
+FROM gcr.io/google_appengine_qa/debian
 ENV DEBIAN_FRONTEND noninteractive
 
 # Update debian 
````

**Comment by ludoch** [comment]
MY numbers on same images:

wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t160327-dot-jetty9-work.appspot.com/dump/info/9.3.5-4core
Running 5m test @ http://20160425t160327-dot-jetty9-work.appspot.com/dump/info/9.3.5-4core
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   127.07ms   53.88ms   1.07s    91.31%
    Req/Sec     8.54      2.82    20.00     76.84%
  Latency Distribution
     50%  112.75ms
     75%  137.15ms
     90%  169.22ms
     99%  347.83ms
  241820 requests in 5.00m, 1.70GB read
Requests/sec:    805.82
Transfer/sec:      5.80MB


 wrk -c 100 -t 100 -d 300 --timeout 5 --latency http://20160425t161451-dot-jetty9-work.appspot.com/dump/info/9.3.8-4core
Running 5m test @ http://20160425t161451-dot-jetty9-work.appspot.com/dump/info/9.3.8-4core
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   111.66ms   45.59ms   1.22s    92.39%
    Req/Sec     9.16      2.65    20.00     86.02%
  Latency Distribution
     50%  101.58ms
     75%  117.48ms
     90%  143.97ms
     99%  252.99ms
  273397 requests in 5.00m, 2.01GB read
Requests/sec:    911.03
Transfer/sec:      6.85MB

**Comment by gregw** [comment]
@ludoch So you are seeing a performance difference only on the single core?   I saw it on the 4 core as well, but I didn't get a chance to test as much as I did on the 1 core machines.

So for 1 core, you are seeing about a 15% performance difference, which is in line with my observations.

**Comment by aozarov** [comment]
@gregw I am trying to run a different test (for compat and using testwebapp).

I am trying to compare the async branch to a modified async branch using the master parent image for openjdk8.

1. do you see a value in doing that.

2. Can I achieve that by modifying ./jetty9-compat/src/main/docker/Dockerfile to use `gcr.io/jetty9-work/jetty9:9.3.8-qa` which you mentioned above.

3.  If so, I was trying to build it `mvn clean install` but failed on some permission issue:
```[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.2:build (build-gae) on project jetty9-compat: Exception caught: Error: Status 403 trying to pull repository jetty9-work/jetty9: "Unable to access the repository: jetty9-work/jetty9; please verify that it exists and you have permission to access it (no valid credential was supplied)."```

Any suggestions?

**Comment by gregw** [comment]
Ludo,

attached is the dump-webapp [dump-webapp.zip](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/files/241673/dump-webapp.zip) project. It uses exactly `gcr.io/jetty9-work/jetty9:9.3.8-qa`  so I'm not sure why you cannot access it?

It is still in the image repository?

I'm out for the next few hours, but if you have failed to build the compat images by then, I will do it this afternoon.

**Comment by ludoch** [comment]
same permission error there... You must be the sole owner of the image bits
on GCS.
Let me change some permissions there.

**Comment by ludoch** [comment]
Or you must be running the build from a VM owned by the same project (for
ex, the Cloud Shell), so there is might be fine.

**Comment by ludoch** [comment]
I filed an internal bug, the behavior is not the expected one.

**Comment by aozarov** [comment]
Here are the results of my tests

Using the async branch as is:

```
[INFO] Status: Downloaded newer image for gcr.io/google_appengine/jetty9-compat:githubheadasync

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   335.75ms  453.33ms   3.67s    87.47%
    Req/Sec     7.77      3.51    20.00     86.17%
  Latency Distribution
     50%  152.71ms
     75%  319.30ms
     90%  948.55ms
     99%    2.54s 
  143379 requests in 5.00m, 160.19MB read
  Socket errors: connect 0, read 0, write 0, timeout 99
Requests/sec:    477.77
Transfer/sec:    546.62KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   287.67ms  418.55ms   3.49s    87.71%
    Req/Sec     8.71      3.39    20.00     72.85%
  Latency Distribution
     50%  112.51ms
     75%  234.79ms
     90%  828.15ms
     99%    2.34s 
  172369 requests in 5.00m, 192.75MB read
  Socket errors: connect 0, read 0, write 0, timeout 142
Requests/sec:    574.38
Transfer/sec:    657.72KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   292.94ms  432.19ms   3.90s    87.86%
    Req/Sec     8.66      3.33    20.00     71.89%
  Latency Distribution
     50%  121.39ms
     75%  229.00ms
     90%  830.04ms
     99%    2.49s 
  176743 requests in 5.00m, 197.63MB read
  Socket errors: connect 0, read 0, write 0, timeout 48
Requests/sec:    588.95
Transfer/sec:    674.36KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   354.58ms  490.05ms   3.63s    86.67%
    Req/Sec     8.08      3.82    20.00     84.62%
  Latency Distribution
     50%  171.66ms
     75%  357.54ms
     90%  971.99ms
     99%    2.74s 
  145777 requests in 5.00m, 163.01MB read
  Socket errors: connect 0, read 0, write 0, timeout 63
Requests/sec:    485.76
Transfer/sec:    556.23KB
```

Using a modified async branch (image gcr.io/ozarov-flex/jetty9-compat:9.3.8-qa - A current async build based on jetty9:9.3.8-qa given bty @gregw):

```
[INFO] Status: Downloaded newer image for gcr.io/ozarov-flex/jetty9-compat:9.3.8-qa

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   346.24ms  460.55ms   4.03s    87.43%
    Req/Sec     7.42      3.49    20.00     84.57%
  Latency Distribution
     50%  160.99ms
     75%  319.73ms
     90%  948.48ms
     99%    2.55s 
  133689 requests in 5.00m, 149.41MB read
  Socket errors: connect 0, read 0, write 0, timeout 108
Requests/sec:    445.48
Transfer/sec:    509.80KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   380.52ms  490.80ms   4.16s    84.93%
    Req/Sec     6.93      3.79    20.00     79.64%
  Latency Distribution
     50%  200.32ms
     75%  427.15ms
     90%  991.09ms
     99%    2.68s 
  118321 requests in 5.00m, 132.31MB read
  Socket errors: connect 0, read 0, write 0, timeout 185
Requests/sec:    394.27
Transfer/sec:    451.47KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   390.57ms  523.29ms   3.71s    85.84%
    Req/Sec     7.09      3.72    20.00     81.75%
  Latency Distribution
     50%  198.19ms
     75%  430.93ms
     90%    1.11s 
     99%    2.90s 
  119749 requests in 5.00m, 133.90MB read
  Socket errors: connect 0, read 0, write 0, timeout 192
Requests/sec:    399.03
Transfer/sec:    456.89KB

$ wrk -c 100 -t 100 -d 300 --timeout 5 --latency https://ozarov-flex.appspot.com/
Running 5m test @ https://ozarov-flex.appspot.com/ 100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   397.32ms  534.54ms   3.71s    87.44%
    Req/Sec     6.90      3.70    20.00     79.58%
  Latency Distribution
     50%  203.15ms
     75%  422.89ms
     90%    1.11s 
     99%    2.92s 
  116867 requests in 5.00m, 130.70MB read
  Socket errors: connect 0, read 0, write 0, timeout 204
Requests/sec:    389.45
Transfer/sec:    446.00KB
```

So, in this tests it actually looks like the async branch, as is, is actually doing better though maybe
one reason is that in the other case we get many more timeouts.

**Comment by gregw** [comment]
Closing for now.  Performance testing should become an ongoing task rather than a specific issue.
