### ISSUE TITLE
Web.xml error-page is not used

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#21]
See https://github.com/GoogleCloudPlatform/appengine-java-vm-hello/issues/3

**Comment by janbartel** [comment]
The problem is that the CommitDelayedResponse class delays the response until after the request has left the context, but the response needs the context in order to select the correct set of error pages.

Ideally we would remove the CommitDelayedResponse class.

**Comment by ludoch** [comment]
Great! After release 1.9.26, we'll have  new environment that will allow us to not use CommitDelayedResponse anymore...We'll have to keep the old environment behind a flag to not break old workflow for a while, but the plan is to only use the new env for all the apps in Q3, so this issue should resolve. We'll introduce a flag that can control the switch, and when doing that we'll be fine with the new env.
(Will need a test, that we can do as well).
