### ISSUE TITLE
remove useless warning

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#215]
See the thread at http://stackoverflow.com/questions/36484232/gae-java-flexible-environment-jsp-warning

**Comment by gregw** [comment]
The class com.google.apphosting.vmruntime.jetty9.InstanceManagerImpl exists neither in master nor async branch?   I'm guessing it is an implementation of JSPs org.apache.tomcat.InstanceManager ?

**Comment by janbartel** [comment]
@ludoch is this coming from some jsp precompilation step perhaps?

**Comment by ludoch** [comment]
yes, this is coming from the internal code supporting the (ancient now) java7/jetty9.2 image.
We do not need this instanceManagerImpl in  github and we reuse the default impl of the instancemanager.
We can close this bug, as it cannot be fixed in github.
