### ISSUE TITLE
jetty-9.2 image misconfigured for Stackdriver Debugger

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/appengine-java-vm-runtime#221]
Hello,

First of all, is jetty-9.2 image (JDK7/Jetty9.2, gcr.io/google_appengine/java-compat) still active? I believe this image is in the jetty-9.2 branch. 

There is a reference to this image in this [doc](https://cloud.google.com/appengine/docs/flexible/java/migrating-an-existing-app?authuser=2#deploying_your_app). I assume the image is active and mainly for migration from standard to flexible. This [doc](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build) also points the image to this repo.

Given that this image is active, we need to fix an issue. I discovered that it is misconfigured for Stackdriver Debugger.

Internal bug number: 27900546

**Comment by chanseokoh** [comment]
Opened another bug to track this Java7/Jetty9.2 issue: 28217727

**Comment by ludoch** [comment]
JDK7/Jetty9.2, gcr.io/google_appengine/java-compat is active (we want to deprecate it but it is active)
and developed inside Google, not on GitHub, so if we want to fix the debugger, it has to be done inside Google repo, not here.

**Comment by chanseokoh** [comment]
Thanks, Ludo. I'm closing this issue.
