### ISSUE TITLE
Is it possible to programatically toggle on/off the session?

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#228]
/cc @gregw

**Comment by janbartel** [comment]
@aozarov  not sure exactly what you want to do here, so let me just describe one scenario. If you need to do something different please let me know.

Session management is configured by calling org.eclipse.jetty.webapp.WebAppContext.getSessionHandler().setSessionManager(SessionManager).

For the compat stuff this is done in the com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.init() method (the VmRuntimeWebAppContext being a subclass of WebAppContext), based on the setting in appengine-web.xml: https://github.com/jetty-project/appengine-java-vm-runtime/blob/async-support/jetty9-compat-base/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java#L329  If there is no appengine-web.xml or it does not enable sessions, then jetty will default to using our own HashSessionManager, which is a non-clustered, in-memory-only session store.

Note that for the compat docker deployment the init() method is explicitly called by the root.xml file that describes the webapp deployment into jetty.

Have a look at the JettyRunner class at https://github.com/jetty-project/appengine-java-vm-runtime/blob/async-support/jetty9-compat-base/src/test/java/com/google/apphosting/vmruntime/jetty9/JettyRunner.java  for an example of how things hook together programmatically for the test environment.

So long as you have a handle to the VmRuntimeWebAppContext instance then you should be able to change what session manager is used by calling getSessionHandler().setSessionManager(SessionManager).  Just make sure that you stop the webapp context before you change the session manager.

**Comment by aozarov** [comment]
Thank you for the details. What I was looking for is to find the easiest way to understand the cost of the session management for *apicompat* by compering similar requests with session on and off.

I would have liked to do that without re-creating and deploying a new Docker image (only differentiated by `session-enabled` value), though maybe that would be the "cleanest" way to do it.

If I understood your response in #229 correctly then I can achieve that by comparing similar requests but one never calls getSession (and therefore I imagine never generates a cookie header) and another one that calls **and** modify the session for each call. I can toggle such behavior using a param in the HTTP request.

BTW, I assume that the test loading tool that we use, [`wrk`](https://github.com/wg/wrk), is going to re-use the cookie from previous requests for the same thread. Do you happen to know if that is correct?

**Comment by janbartel** [comment]
@aozarov to be sure that no session is created:  ensure request does not contain a jsessionid cookie or encoded in the url; don't use form authentication; don't call Request.getSession(true). 

Correct that you can use http params on requests to control whether you call Request.getSession(true/false) and whether you modify the session - and yes, to be sure that the session is written out it would be best to modify an attribute.

Worth noting too that the compat session code uses a backoff algorithm to retry failed session writes: it will retry up to 10 times, starting with delay of 50ms before retry and doubling the retry timeout each retry.

@gregw knows more about the wrk tool, I'll assign for him to comment.

**Comment by aozarov** [comment]
Thank you. BTW, are the session retry numbers configurable per session storage type?
See [here](https://cloud.google.com/datastore/sla) for the Datastore back-off that are needed to meet the SLA.

**Comment by gregw** [comment]
I believe that the `wrk` tool does not send cookies and thus it does not preserve sessions.  Thus the early load tests done with `wrk`, which hit a servlet that called `getSession(true)` and was creating a new session for every request... which was then never accessed again.    I think `wrk` is a highly unrealistic load generator, perhaps it can be configured better, but I simply change to requests that did not access the session.

**Comment by gregw** [comment]
@janbartel I'm backing off to you for the backoff question

**Comment by janbartel** [comment]
Both the backoff interval (50ms) and the backoff attempts (10) appear to have been hardcoded in the com/google/apphosting/runtime/jetty9/SessionManager.java 

The SLAs for GCloudDataStore say a client should do a retry of max initial interval of 1 sec and backoff up to 32 sec - obviously for a webapp that uses sessions having the container potentially having to wait up to 32 sec for each each request to finish would be awful for latency and also eventually throughput.

I should also mention that there is an async variant of the gcloud session data store: [DeferredDatastoreSessionStore.java](https://github.com/jetty-project/appengine-java-vm-runtime/blob/master/appengine-managed-runtime/src/main/java/com/google/apphosting/runtime/DeferredDatastoreSessionStore.java).  That appears to use a task queue to queue up session writes to the gcloud datastore. It appears to be enabled if appengine-web.xml contains asyncSessionPersistence=true, but I'm not sure if that is something that the user has to enable, or something that the infrastructure generates, or even if that api is still offered by the gcloud datastore.

**Comment by aozarov** [comment]
We *don't* have to try until we reach for 32 seconds, however violating the SLA by retrying too soon does not seem to me something *we* should do.

Yes, looks like `async-session-persistence` still [exists](https://cloud.google.com/appengine/docs/java/config/appref) , however that could not be implemented using Google Cloud Datastore as such operation is not supported [yet?]
@ludoch  is it something that we plan to support?

**Comment by ludoch** [comment]
1/ we cannot support async-session-persistence in the initial
implementation (would need cloud task queue to be ready, and tightly
integrated with DS transactions.
2/ Best effort for SLA is nice, but not up to 60s.. I think the key point
there is the 1 sec retry .

**Comment by ludoch** [comment]
Fixed in Async
