### ISSUE TITLE
Are session loaded lazily (upon the first call of getSession) and only saved if dirty?

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#229]
/cc @gregw

**Comment by janbartel** [comment]
When a request enters the handler chain, the jetty SessionHandler will find a session cookie or jsession id encoded url on the request and ask a SessionManager to look up the session. In the appengine compat code the Session Manager lookup goes to memcache first and then falls through to gcloud datastore.  The data of the session is populated into a fresh AppEngineSession object.  

A session is written to gcloud datastore and memcache when the request is exiting the server, as it is about to be destroyed. It is only written out iff the session is dirty, which occurs if either:

- set/removeAttribute was called on the session

- time remaining until the session expires is at least 75% of the session timeout

The latter has the effect of avoiding frequent writes of a session where all that changed was the expiry time (last access time).

Because session objects are not shared amongst simultaneous requests with the same session id, it is non-deterministic what is stored as the requests exit: if request A sets attribute X and request B sets attribute Y, it depends on what order the requests complete as to whether the stored session will contain attribute X or Y (it is impossible for it to contain both X and Y).

**Comment by aozarov** [comment]
I see, thanks. So, it looks like if I want to have a test that shows the difference between session on or off I actually need to use the session.

BTW, what will happen if I use the session but `appengine-web.xml` has `<sessions-enabled>false</sessions-enabled>`?

**Comment by janbartel** [comment]
More details on sessions are in my posts on issue #228.  To recap part of what I said there, if <sessions-enabled>false</sessions-enabled> in appengine-web.xml, then jetty falls back to using our in-memory-only, non-clustered HashSessionManager.

**Comment by aozarov** [comment]
Yes, thank!

I do wonder however if that is not confusing. In that case I would have called the option persistent-sessions-enabled instead (as to me sessions-enabled false suggest no sessions, hence session cookie  never sent back).

**Comment by gregw** [comment]
@aozarov  The fallback to HashSessionManager predates our involvement, so I'm not entirely sure why it was done (and I agree it is confusing).

it would be easy to totally remove the SessionHandler (or not add it in the first place) if sessions-enabled is false.      This would mean a session cookie would never be set and getSession would always return null.

If that is desirable, label this issue as an enhancement and assign to me and I'll make it so!

**Comment by janbartel** [comment]
@gregw IIRC the compat code used to have a stub session manager if sessions were not enabled. I think it threw exceptions if sessions were tried to be accessed causing problems with some frameworks. So now if sessions are not enabled there is no session manager set and the SessionHandler just falls back to the default Hashsessionmanager. See issue #15 I think.

**Comment by gregw** [comment]
Oh - I missed that change.  I think that using the hash session manager is confusing and we should probably revert to either no session manager (null always returned from getSession()) or a better stub session manager that avoid the exceptions.   I think the solution to #15 perhaps should have just been to give an info log that a noop session was being used?

**Comment by janbartel** [comment]
I think some frameworks might call getSession(true) and not expect that it would ever return null, so not sure if a new StubSessionManager would be helpful.

**Comment by aozarov** [comment]
+1 for NoOp Session manager when sessions are disabled. Basically a session manager that does not throw exception however never returns values (as if all values are immediately expired).

**Comment by ludoch** [comment]
+1.
We used to have this (still has it in the standard GAE), and was removed in
https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/commit/72c167096494652efb34ea08025af3db23b6106e
I am fine reinstalling a stubsession manager (or better rename to noop
session manager.

**Comment by janbartel** [comment]
To be sure we're solving this the correct way, what is it that we are trying to achieve? Does <sessions-enabled> in appengine-web.xml in reality refer to  the use of _persistent_ sessions? I can see a webapp explicitly enabling persistent sessions but I can't see the point of explicitly disabling non-persistent sessions.  In other words,  what is the benefit of replacing the HashSessionManager with a NoOpSessionManager that does not retain session attributes even for the duration of the request?

**Comment by janbartel** [comment]
Let's consider the specifics. What should be the behaviour of a session manager when sessions-enabled == false:

- should request.getSession(true) return null or a non-null value?
Assuming non-null:
- should session.setAttribute(key,val) followed by session.getAttribute(key) return val or null?
- should the session id be a random value or always the same value?
- should the session cookie ever be set? Should a session id ever be encoded onto a url?
- should cross-context request dispatch ever share a session id?
- should any session listeners ever be called?

**Comment by aozarov** [comment]
The goal is that if an application is deployed with session-enabled set to `False` there would be no *visible* session management. Hence, no cookie sessions sent back and *every* request starts with a new clean session state.

On the server side I don't think we should barf if session API is used while session is disabled but using that API should not have any side effects once request was completed.

- should request.getSession(true) return `null` or a non-null value?

non-null No-OP session
- should session.setAttribute(key,val) followed by session.getAttribute(key) return val or null?

I think we should return `null`. is that a violation of the API/specification?
Though returning val (and dropping it at the end of the request) may be a more "app-friendly"
implementation, I think it does complicate things dealing with the other items you mentioned
later (request forwarding and listeners. Also, I am not sure what is the expected behavior
for async api/callbacks using the session).

- should the session id be a random value or always the same value?

I think we should pick random value at the beginning of the request and stick to it during that request.
- should the session cookie ever be set? Should a session id ever be encoded onto a url?

I don't think we should.
- should cross-context request dispatch ever share a session id?

I don't see why not. If we pick return `null`, it should be seen as an empty session.
- should any session listeners ever be called?

Similar to cross-context request dispatch, if the session would be seen as empty I am not sure I see
any harm in invoking the listeners.

**Comment by gregw** [comment]
Note that cross context dispatch is not really an issue for compat as there is only 1 context.   So I think having a random session ID is fine.

I'm in two minds about if getAttribute should work within the scope of a request dispatch.   This may help frameworks that are miss using sessions to pass parameters, but doing so may also confuse developers into thinking they have a working session when a fail fast result would be better.

On balance, the only reason to return a non null session when session management is turned off is to spoof frameworks that must use a session, so I think having getAttribute return a value is probably best.

**Comment by gregw** [comment]
@janbartel I've switched this to an enhancement, can you implement.

**Comment by aozarov** [comment]
I think all questions and action items for this issue were addressed, so I am closing it.
Please re-open if I missed something.
