### ISSUE TITLE
Servlet 3.1 Async feature does not work in Managed VM, all servlets in webdefault.xml have async:false

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#23]
From a customer:

The main problem is in Google Filters. They do not support asyncRequest attribute. It prevents async feature of Servlet 3.0. Default web.xml should looks like:

    <filter>
        <filter-name>AbandonedTransactionDetector</filter-name>
        <filter-class>
            com.google.apphosting.utils.servlet.TransactionCleanupFilter
        </filter-class>
        <async-supported>true</async-supported>
    </filter>

    <filter-mapping>
        <filter-name>AbandonedTransactionDetector</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    
    
    
    
    <filter>
        <filter-name>SaveSessionFilter</filter-name>
        <filter-class>
            com.google.apphosting.runtime.jetty9.SaveSessionFilter
        </filter-class>
        <async-supported>true</async-supported>
    </filter>

    <filter-mapping>
        <filter-name>SaveSessionFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    <filter>
        <filter-name>_ah_ParseBlobUploadFilter</filter-name>
        <filter-class>
            com.google.apphosting.utils.servlet.ParseBlobUploadFilter
        </filter-class>
        <async-supported>true</async-supported>
    </filter>

    <filter-mapping>
        <filter-name>_ah_ParseBlobUploadFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

From Jeremy:
The filters in particular need to support async so that the servlets they wrap can as well. This changes the design pattern as the old
  try {
    // prepare
    chain.doFilter();
 } finally {
    // clean up
 }

pattern can't be used. Instead, the filter needs to detect if async has been started in the return path and/or whether this is an async dispatch in the prepare part. It may also need to add listeners to the AsyncContext in case the request gets completed in the background. 

It's all quite messy. It may be easier to convert some of the Filters to ServletRequestListeners.

The other issue is that the request may be processed on multiple threads so the ApiProxy context can't rely on a simple ThreadLocal. Specifically, AsyncContext#start "may" pass contextual information when executing the Runnable and we probably should so that applications can make API calls from background tasks. Doing this from user-land is messy so we should handle it within the container.

**Comment by gregw** [comment]
The anointing of threads with threadlocals for google API calls should be moved from the extended doScope method of the ContextHandler, to a listener mechanism that can also be triggered from calls to AsyncContext.start(Runnable) and async dispatches (eg onWritePossible).  This will allow a single mechanism to setup threadlocals for async and blocking.   

Only then can we look at updating the filters to support async (or better yet removing some of the filters completely).

**Comment by gregw** [comment]
Note that this may need some changes to the jetty distro, so I will be able to do for the 9.3 branch easily.   I can also do for the 9.2, but would prefer to avoid that if timing allows.

**Comment by ludoch** [comment]
New Pull request to review:
https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/pull/110
Tomas and Anthony should help on the review

**Comment by aozarov** [comment]
I believe this is no longer an issue in the assync-support branch. @gregw ?

**Comment by gregw** [comment]
this is fixed in Async branch.    We had created the label to mark this before closing these issues when it is merged.  But we can close now also.

**Comment by aozarov** [comment]
I think we were not consistent with using the label or closing the issue and therefore I suggest that we close anything that was fixed in async. It would be good to do the clean-up, so we can know what exactly is pending. @ludoch ?

**Comment by ludoch** [comment]
Agree. Let's close issues fixed in the branch.
