### ISSUE TITLE
Update the main README to mention installing Docker as a pre-requisite to "mvn install"

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#235]

**Comment by aozarov** [comment]
Also, I am not sure what "...or environment variables pointing to a remote docker instance" is referencing to and what would be that environment variable. /cc @ludoch

**Comment by ludoch** [comment]
You can add Docker flags in the Docker maven plugin section...

For example, for me, using the MacOSx Docker client Beta, I need to put:

`      <configuration>`
`            <dockerHost>unix:///var/run/docker.sock</dockerHost>`
`          </configuration>`

For others,  docker host or port might be handy, if not the default values. 
See docker-machine env default in https://docs.docker.com/engine/installation/mac/ for example.

**Comment by aozarov** [comment]
Fixed by #238
