### ISSUE TITLE
Reduce log level for VmApiProxyDelegate

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#242]
We should change VmApiProxyDelegate logging (e.g. for `makeApiCall`) to DEBUG (Using `LogLevel.FINE`).  Currently every request would have at least 4 separate log entries for, I guess, the session management (2 for datastore and 2 for memcache).

Also, I think we should start adding `'traceId' to the structured log metadata (which hopefully will allow combining related log lines).

**Comment by gregw** [comment]
See comment on #240 for traceId
