### ISSUE TITLE
Origin port not set for jetty-compat-base running locally

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/appengine-java-vm-runtime#245]
The origin port for requests is not set when running the jetty9-compat-base locally (ie outside a google firewall).

This means that response.sendRedirect(location) produces an encoded location missing the port. Eg if response.sendRedirect("/foo") is called, the location header produced is "http://localhost/foo" instead of "http://localhost:8080/foo".

**Comment by ludoch** [comment]
I guess we can close this one?
