### ISSUE TITLE
Need to use gcloud dev servers for jetty9-compat-base running locally

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/appengine-java-vm-runtime#246]
When running the jetty9-compat-base locally, we need access to local memcache and local gcloud datastore dev servers.

**Comment by aozarov** [comment]
Maybe we can use the "$GAE_PARTITION" = "dev" check to disable memcache when running on localhost?

**Comment by gregw** [comment]
obsoleted by  https://github.com/GoogleCloudPlatform/jetty-runtime/issues/5
