### ISSUE TITLE
We should rethink the memory settings we use for the Java heap

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#247]
Currently in [jetty_run.sh](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/master/appengine-jetty-managed-runtime/src/main/docker/jetty_run.sh) we specify the heap
as MemTotal * 0.8 - 400MB (400MB is used by the VM). As, I think, the jvm uses more memory than just the heap (e.g. native thread stack, 1MB per thread) we may not have enough memory on smaller Vms.

**Comment by sbordet** [comment]
See #243 too.

**Comment by aozarov** [comment]
Oh, good. wasn't ware of it. Closing it as as a dup of #243
