### ISSUE TITLE
Review our Jetty xml files with respect to our context

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#25]
Context class is at https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/master/appengine-jetty-managed-runtime/src/main/java/com/google/apphosting/vmruntime/jetty9/VmRuntimeWebAppContext.java

Do we have duplicate settings in xml and this class?

**Comment by gregw** [comment]
setAggregationBufferSize code can (or should) be done in XML rather than in code.   I suspect that the instancecheck is not working anyway.

**Comment by gregw** [comment]
Fixed in PR #28
