### ISSUE TITLE
mvn clean test failing

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#262]
In the async-support branch a `mvn clean test` fails, but `mvn clean install` passed

**Comment by gregw** [comment]
@joakime you might want to have a look at this also

**Comment by joakime** [comment]
Some problems identified in the build that need to be fixed:

* The docker-maven-plugin isn't run in the 'mvn clean test' build, making the reference later in the 'mvn clean test' invalid
* The manual use of maven-resources-plugin needs to be fixed to use the //build/resources instead (the current build puts maven-resources-plugin in the wrong places in the build lifecycle)
* The use of maven-dependency-plugin:copy-dependencies *must* be after the `package` phase in the (such as in `/jetty9-base/`), and it currently isn't being used that way.

**Comment by joakime** [comment]
After a review, the tests that use docker are not going to work on the `test` phase, but rather the `integration-test` phase.

See: http://maven.apache.org/ref/3.3.1/maven-core/lifecycles.html

All of the docker related tests need to go through the `package` phase properly for it to be sane.  Putting the docker related testing in `integration-test` is the most sane way to accomplish this.

Working on a good PR for this approach.

**Comment by joakime** [comment]
In fact ....

Use `mvn clean integration-test` now, it works.

I will still submit a PR for fixing up the `<build><resources>` issues discovered in this analysis.

**Comment by aozarov** [comment]
I think mvn clean test should work too, though I imagine, run only the tests that are not consider "integration test". I guess one way to separate them is by naming convention and using ITXXX for integration tests?

**Comment by joakime** [comment]
All of the docker related creation / building will need to be the "line in the sand".  if the module does anything with docker, it needs to be at the `package` phase as well.  The regular `test`s cannot rely on Docker or anything docker related or created to function.

**Comment by aozarov** [comment]
Yes, I understand that. Are you saying we don't have any unit-tests that don't depend on docker?

**Comment by joakime** [comment]
The tests are being evaluated ATM, seeing where each would live. stay tuned.

**Comment by joakime** [comment]
So far, everything  in `jetty9-compat-base` would be an integration test.

This is because the `dependency:copy` (for `jetty9-base`, and `testwebapp.war`) cannot work in a reactor build that hasn't had the `package` phase executed for those projects (note: `package` is a phase after `test`).  Making the requirements for the tests in `jetty9-compat-base` invalid for the `test` phase.

**Comment by joakime** [comment]
Here's an interesting question (coming from an [emeritus apache maven pmc member](http://maven.apache.org/team-list.html#joakime) no less!)...

Since so many other Google projects seems so enamored with gradle, why is this build not using gradle?  (Or to put it a different way, is there an expectation for this project to be gradle-ized in the future to conform to some Google project policy?)

**Comment by aozarov** [comment]
I don't think we should ditch maven anytime soon. There are many users using it and many of our tools are built around it. However +1 for Making our build support both maven and gradle. 

I don't think there is any strict policy about it so far. Some google projects are using only maven (guava, guice,...) and others (not as many) use gradle (such as grpc-java and looking at their gradle config [file](https://github.com/grpc/grpc-java/blob/master/build.gradle) makes my head spin).

**Comment by aozarov** [comment]
Fixed by #275

**Comment by aozarov** [comment]
@joakime  Though the build completes fine are you sure the it/... tests are actually running upon install, verify or integration-test?

**Comment by joakime** [comment]
Will manually declare the failsafe plugin (configuration & version) in the top level pom.
Stay tuned.

**Comment by joakime** [comment]
Closing, as PR #283 is applied
