### ISSUE TITLE
Fix the env settings for enable/disable debugger

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/appengine-java-vm-runtime#267]
Currently they are set as `DBG_ENABLED` and `CDBG_DISABLE`. We should make their names consistent. 

Also, flag are set to be on or off based on being an empty string or not.
We should consider applying a boolean value check.

For more info see #266

**Comment by gregw** [comment]
To plan this change, we need to work out external dependencies:

- CDBG_DISABLE is used within `/opt/cdbg/format-env-appengine-vm.sh` which is imported from [cdbg_java_agent.tar.gz](https://storage.googleapis.com/cloud-debugger/appengine-java/current/cdbg_java_agent.tar.gz)
- DBG_ENABLE is used only with scripts from this project, but is listed in [documentation](https://cloud.google.com/appengine/docs/flexible/java/migrating-an-existing-app#move_your_app_into_the_flexible_environment), which can be changed in the core doco, but not in [many links](https://www.google.com.au/webhp?q=DBG_ENABLE+appengine).
- the current `setup-env.bash` assumes that a `/opt/cprof/format-env-appengine-vm.sh` file exists that is called if CPROF_ENABLE is set, but that script is no longer in the import of [cloud_profiler_java_agent.tar.gz](https://storage.googleapis.com/cloud-profiler/appengine-java/current/cloud_profiler_java_agent.tar.gz). So it appears that this dependency has changed and we've not noticed.

**Comment by chanseokoh** [comment]
About CDBG_DISABLE:

Stackdriver Debugger is enabled by default on all runtimes, the only exception being the Java runtimes. This exception in Java seems to be due to some unfortunate mishap, and we fixed it a while ago after noticing it (#219). Note that CDBG_DISABLE is inherent to the Stackdriver Debugger design. Because the debugger is enabled by default, people needed a way to disable it for various reasons, so it was decided to use this variable. The name of the variable cannot be changed as this variable is being used across several internal systems.

**Comment by aozarov** [comment]
@chanseokoh in that case shouldn't we change the check in this [line](https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/blob/async-support/openjdk8/src/main/docker/setup-env.bash#L8) to -z "${CDBG_DISABLE}" ?

If so, we should also update the doc which I think you suggested in #226 that you will do?

**Comment by chanseokoh** [comment]
I don't know the history about what happened on the Java App Engine runtimes, but DBG_DISABLE might only controlling a local Java debugger and have nothing to do with the Stackdriver Debugger. Perhaps, someone mistakenly decided to also put the Stackdriver Debugger under DBG_DISABLE at some point.

On the other hand, CDBG_DISABLE is only about the Stackdriver Debugger. 'C' in CDBG stands for 'Cloud'. The name before re-branding to Stackdriver was Cloud Debugger.

**Comment by chanseokoh** [comment]
Sorry. DBG_ENABLE, not DBG_DISABLE in my previous comment. To repeat, what I am saying is that that env var might actually be meaning 'LOCAL_DBG_ENABLE'. (Not certain about exact context around the var though.)

**Comment by aozarov** [comment]
And do you think that is the right decision? I mean any reason for not having one flag to toggle debug in local or production?

**Comment by gregw** [comment]
Perhaps to keep consistent with naming, the documentation and other resources we need to adopt the logic that the debugger is enable unless DBG_ENABLE is set to 'false' or CDBG_ENABLE is set to 'false' or CDBG_DISABLE is set to anything.

Then we change CPROF_ENABLE and ALPN_ENABLE to check for boolean values and remove all references to CPROF_DISABLE and ALPN_DISABLE

**Comment by aozarov** [comment]
@chanseokoh can you give us some background on CPROF_ENABLE (and cloud_profiler_java_agent.tar.gz which its content seems to be specific to dataflow and is missing
the format-env-appengine-vm.sh file which the scripts were depending on)?

**Comment by chanseokoh** [comment]
I guess @ludoch should know about the current script setup revolving all these variables?

**Comment by ludoch** [comment]
Nope...

**Comment by aozarov** [comment]
@gregw we plan to remove the CPROF_ENABLE option. /cc @rauls5382

Also, I think we should simplify and have only one option for each feature.

How about ALPN_ENABLE and CDBG_ENABLE which can be set to `true` or `false`.

We should also document what is the "default" mode for each (`true` for CDBG_ENABLE
and `false` for ALPN_ENABLE) and let our scripts evaluate the value and possiblity
create more settings (such as CDBG_DISABLE) that may be used the the scripts we
delegate to (such as `/opt/cdbg/format-env-appengine-vm.sh`).

Though a bit more work on our side I think it will be more clear to the users.

**Comment by aozarov** [comment]
Reference to CPROF_ENABLE was removed in #273

**Comment by gregw** [comment]
@aozarov I think your suggestion is the best so far.   Just have single ENABLE attributes per feature which we document externally and then internally set/clear the  DISABLE variable (or probably just not call the script).    I'll prepare a PR to that effect today.

Note also that for the open source project it would be good to document in these issues why CPROF has been removed.  Has it be replaced by something else?

**Comment by aozarov** [comment]
> Note also that for the open source project it would be good to document in these issues why CPROF has been removed. Has it be replaced by something else?

@rauls5382 can probably provide more information. I think it actually never worked.

**Comment by gregw** [comment]
@aozarov if the cloud debugger is no longer called Cloud Debugger, then is CDBG_ENABLE still the right name?  Maybe stick with DBG_ENABLE?

**Comment by chanseokoh** [comment]
@gregw Don't forget that DBG_ENABLE is currently tied only to a local Java debugger, which is disabled by default. On the other hand, Stackdriver Debugger is enabled by default, so consider the possibility that mixing these two debuggers under a single variable many confuse users, particularly because their default values are different.

**Comment by ludoch** [comment]
DBG_ENABLE was used when we could do local Docker run in the Cloud SDK.
Cloud SDK local execution of a Docker image has been currently removed, so
that start a local debugger now is not controlled with this variable
anymore.

**Comment by aozarov** [comment]
My preference would be to have the same variable control local (when we support it) or production debugging (same option would work for both, and I think default value could be different as long as it is documented). I assume it would be possible to override the value upon docker run when running locally
using the `-e` flag.

Also, I think that DBG_ENABLE is a better name and we should use it and create anything else needed for the scripts we delegate.

**Comment by rauls5382** [comment]
Like Arie said, CPROF has never worked in this environment, so it shouldn't
have been added in the first place.


Raúl E Silvera | SWE | rsilvera@google.com | *408-789-2846*

**Comment by aozarov** [comment]
I think this can be closed unless @gregw wanted to keep it open until #279 is fixed?
