### ISSUE TITLE
Health check logging levels based on error

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/appengine-java-vm-runtime#282]
As a result of comment from @aozarov from Issue #231, we should alter the logging levels based on If the Health Check results in 200, it should be a DEBUG/FINE level event, and all other results should be a higher level.

I favor WARN for non-200 results.

**Comment by gregw** [comment]
obsoleted by https://github.com/GoogleCloudPlatform/jetty-runtime/issues/4
