### ISSUE TITLE
Google Code Style: does not like multidimensional arrays

### ISSUE THREAD

**Issue by joakime** [GoogleCloudPlatform/appengine-java-vm-runtime#291]
The current Checkstyle for Google Code Style does not like multi-dimensional arrays.

eg:
```java
   String expected[][] = new String[] { {"a", "b"}, {"c", "d"} };
```

The second set of `[]` after the `expected` is flagged as being out of place.

Requesting a new declared suppression of whatever checkstyle test it is that triggering this and excluding testcases from this test (as this is very common for parameterized tests)

**Comment by aozarov** [comment]
What about ```String[][] expected = {{"a", "b"}, {"c", "d"}};```?

**Comment by joakime** [comment]
Ah, the old C vs Java array initializer debate.

Strange that it should flag this way ...

```none
String expected[][] = new String[] { {"a", "b"}, {"c", "d"} };
                  ^--- array index out of place
```

its happy with `expected[]` tho. *shrug*
