### ISSUE TITLE
JMX support?

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#294]
Jetty is fully instrumented with JMX mbeans that allow monitoring, control and debugging of the server.   The JVM also provides useful information via JMX.   

Should we enable JMX in the jetty9 vanilla and/or compat images to enable a remote jmx client to attach? 

Is there any pre-existing support for handling external JMX clients?   

Should we consider embedding a second context with a webapp JMX client?

**Comment by aozarov** [comment]
I think that is a fine idea, though should be considered to only enabled locally accessed when ssh to the machine.

**Comment by gregw** [comment]
Perhaps we should have a setup where the the docker container exposes the JMX port to the compute engine instance, but then not have that exposed on the network.   A ssh tunnel can then be made to the compute engine instance and tools like jvisualvm run locally against the tunneled port.

More of a documentation task as we would not want to run MBeans all the time.  Should only be created if they are intended to be looked at.

**Comment by gregw** [comment]
moved to https://github.com/GoogleCloudPlatform/jetty-runtime/issues/6
