### ISSUE TITLE
GAE naming in jetty9 (non compat)

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#296]
The jetty9 (non compat image) has a module called gae that is used to apply the gcloud relevant configuration.

This module should probably no longer be called gae, not least because it clashes with the module of the same name in jetty9-compat that has different configuration.

**Comment by gregw** [comment]
@meltsufin if the `gae` naming (eg [gae.mod](https://github.com/GoogleCloudPlatform/jetty-runtime/blob/master/jetty9-base/src/main/jetty-base/modules/gae.mod) still appropriate for files/modules in the new jetty-runtime?   should they be `gcp` or `flex`?

Eitherway, please close this issue and if  `gae` is not OK, open a new issue on [jetty-runtime](https://github.com/GoogleCloudPlatform/jetty-runtime)

**Comment by meltsufin** [comment]
I think the `gae` name is OK for now. Compat should probably call its own gae-compat.
