### ISSUE TITLE
 Java/jetty kills the app 5 seconds after SIGTERM

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#302]
A customer is is having problems with the Java runtime stopping the process 5 seconds after we send SIGTERM. The lifecycle PRD specifies that apps should have 30 seconds at least.
Our Jetty.xml has
```
<Set name="stopTimeout">5000</Set>
```

**Comment by ludoch** [comment]
I think we should do the change in the 2 images (master and async)

**Comment by gregw** [comment]
Annoyingly 5000 is hard coded in jetty.xml, which makes it difficult to change.  I have opened https://github.com/eclipse/jetty.project/issues/774 to fix this, but will prepare a PR to work around it for now.

**Comment by ludoch** [comment]
We also need a fix in master

**Comment by ludoch** [comment]
I guess, we would also need that in the pure jetty9 runtimes (master and async?)

**Comment by gregw** [comment]
@ludoch Commit ef87bbaa86b31609059c6f1576f5b69fd30a8a65 did apply the longer time to the pure jetty9 runtime in async.       While there is a gke-jetty in master, it doesn't really have a base directory like we do in async, so a different approach will be needed.   Is that image used?

**Comment by ludoch** [comment]
Someone told me this:
"ah crap, signals are not forwarded in by the jetty_run.sh script
but it seems doable though
http://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash"
???

**Comment by gregw** [comment]
OK, I will update in both master and async; pure and compat.   Shall I use this issue and PR?

**Comment by ludoch** [comment]
sure.

**Comment by ludoch** [comment]
I guess it can be tested via sshing to the docker container?

**Comment by gregw** [comment]
@ludoch that's how I'm testing... standby...
