### ISSUE TITLE
Hiding app.yaml at web app root

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/appengine-java-vm-runtime#306]
It would be good to avoid serving the app.yaml in the staged app's root directory.  Perhaps we could add a snippet to webdefault.xml?

**Comment by janbartel** [comment]
We could use jetty-specific methods of hiding app.yaml. Using security constraints in webdefault.xml would be difficult:  if using quickstart, then the webdefault.xml comes from the sdk and we have no control over it. If not using quickstart then we can of course modify the webdefault.xml.

I would instead suggest that we use the o.e.j.webapp.WebAppContext's support for hiding arbitrary resources. See [here](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L98)  and [here](https://github.com/eclipse/jetty.project/blob/jetty-9.3.x/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L269).  

For the standard jetty image, we can use our DeploymentManager to add a protected target of "/app.yaml" to every deployed webapp.

For compat, (as it does not use the DeploymentManager) we can instead hard-code the exclusion of "/app.yaml" in our WebAppContext subclass.

Of course, it might be best to ensure that the app.yaml is not included in the deployable, if at all possible.
