### ISSUE TITLE
Use standard proxy headers

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#320]
The requests inbound need to be customized to map specific headers to standard APIs.  The headers used in the GAE/Flex environment are:
 - `X-AppEngine-Https` which can be `on`|`off` and affects the `ServletRequest.getScheme` and `ServletRequest.isSecure` APIs of the servlet specification.
 - `X-AppEngine-User-IP` which is set to the users remote IP address and is made available via the 'ServletRequest.getRemoteAddr()` API

There are defacto standard headers that could be used instead of these proprietary headers:
- [`X-Forwarded-For`](https://en.wikipedia.org/wiki/X-Forwarded-For)
- [`X-Forwarded-Proto`](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-proto)

Also there is proposed standard [RFC7239](https://tools.ietf.org/html/rfc7239), which replaces the defacto standard headers with a single header.

The google proxy's should use the either the proposed standard or defacto standard headers so that there is no requirement to adapt 3rd party containers to use the proprietary google headers.

**Comment by gregw** [comment]
I have open and resolved https://github.com/eclipse/jetty.project/issues/834. This will allow the standard jetty distribution to handle `X-AppEngine-Https`  and `X-AppEngine-User-IP`

**Comment by meltsufin** [comment]
Thanks Greg! When is the patched version of Jetty expected to be released so that we can start using that instead of the GoogleRequestCustomizer?

**Comment by meltsufin** [comment]
@gregw @ludoch I just ran a simple servlet on App Engine, and it looks like for `vm=true` we already get
`X-Forwarded-For` header, and on `env=flex`, we get both `X-Forwarded-For`, and `X-Forwarded-Proto`.

**Comment by gregw** [comment]
Ah that's a step in the right direction (and lucky that you didn't step all the way to RFC7239, as we have only just implemented it).

So for now do we want our images to look for both proprietary headers and defacto standard?    Or should we look into the environment to try to guess what headers will be coming and configure only for the them.

I expect releases that contain this fix to be about a month away, but we can escalate if need be.   However, another solution that we can probably do with the existing release is to put a rewrite customizer in place to rewrite the proprietary headers to the standard ones, and then have the standard customizer.  Probably better to accelerate our release as running the extra regexs on every request will burn lots of CPU when added up.

**Comment by meltsufin** [comment]
Assuming that `X-Forwarded-For` and `X-Forwarded-Proto` are set on `env=flex`, if we removed the `GoogleRequestCustomizer`, would everything still function the same with the current version of Jetty we're using?

If we still need the `GoogleRequestCustomizer`, I would prefer it do the minimum work required to compensate for any standard headers that App Engine is not setting.

**Comment by gregw** [comment]
We would need to replace it with the standard request customizer,  so that
is just a small configuration change.  Want a pr for that?

**Comment by meltsufin** [comment]
Sure! Thanks.

**Comment by gregw** [comment]
@meltsufin I just checked [RFC7239]https://tools.ietf.org/html/rfc7239#section-5.2) and [AWS X-Forwarded-For](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html) and both specify that the rightmost (ie last) IP is for the closest proxy and the leftmost is the originating proxy.... which if allowed through could be the client not telling the truth.

**Comment by meltsufin** [comment]
Got it. Thanks for checking!

**Comment by gregw** [comment]
Resolved in new repos with https://github.com/GoogleCloudPlatform/jetty-runtime/commit/fd4eac341de33a303d31375a9449ec33a01d68ec
