### ISSUE TITLE
Use GAE_MEMORY_MB for heap size calculation

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/appengine-java-vm-runtime#322]
Currently /proc/meminfo MemTotal is used, but GAE_MEMORY_MB is the new environment variable that has a more accurate number.

**Comment by gregw** [comment]
I've not yet seen that in the images I've deployed.  For a 4GB instance will that variable be `4096` or `4096M`.

We can change the current setup-env.bash to look for this and only fall back to meminfo if not found, or it may be simpler to just change after the restructure?

**Comment by rdcastro** [comment]
No suffix, only 4096.

**Comment by meltsufin** [comment]
@gregw I think we need to change setup-env.bash so that we use GAE_MEMORY_MB if available, and fall back to /proc/meminfo MemTotal otherwise. The reason being that GKE is not going to have GAE_MEMORY_MB.

**Comment by meltsufin** [comment]
@rdcastro GAE_MEMORY_MB is now available in production for `vm: true` and `env: flex`, but I'm not sure what the new heapsize formula should be.
It used to be:
**heap_size = host_total_memory * 0.8 - 400**.
Should the new formula be
**heap_size = GAE_MEMORY_MB * 0.8**?

**Comment by rdcastro** [comment]
It seems your previous formula was "80% of what is available to the app container". GAE_MEMORY_MB is now the amount available to the app container (which is also enforced via Docker), so I think you can keep the same formula as before if it worked well.

In case it's not documented, please make sure that is documented somewhere so users can understand that if they requested 1Gb, they will only have 800Mb for the Java app, which might not be obvious.

**Comment by meltsufin** [comment]
@joakime do you have some cycles to look at this?

**Comment by joakime** [comment]
The code change has already been made locally.
Time permitting it will have a PR submitted. 
But know that the full cycle for testing even small changes like this can take many hours.

**Comment by meltsufin** [comment]
Great, thanks!

**Comment by gregw** [comment]
replaced by https://github.com/GoogleCloudPlatform/openjdk-runtime/issues/3
