### ISSUE TITLE
NoClassDefFoundError & LinkageError caused by slf4j

### ISSUE THREAD

**Issue by cvlaminck** [GoogleCloudPlatform/appengine-java-vm-runtime#326]
Hi,

We are using Appengine flexible with a custom dockfile to use jetty9-compat:githubheadasync as base image.

Since today, every time we deploy a new version to production, we get NoClassDefFoundError on all classes importing slf4j classes. The same code was running yesterday without any issue. This is a critical issue for us as a lot of libraries we are using in our application is relying on slf4j for logging and therefore we cannot deploy our application anymore.

I also made some experimentation and when I try to get a Logger, I get this issue:
Message: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:306)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)

Our version from Sept 1. 14:00:00 UTC does not have the issue. So it was introduced in live between this date and now.

Have you any insight to share on those issues?

**Comment by jmcc0nn3ll** [comment]
likely related to PR #295 that was merged in yesterday

**Comment by jmcc0nn3ll** [comment]
@cvlaminck Do you have a direct dependency in your webapp on slf4j and if so what version are you deploying with your application?

**Comment by cvlaminck** [comment]
No, we get slf4j by transitivity of our dependencies. The version deployed is 1.7.7.

**Comment by gregw** [comment]
@ludoch It looks like #295 has exposed slf4j in such a way that it is breaking webapps that also use slf4j.    This is probably easily fixable by setting up the server classes on the context, but I'm thinking that it may be better to roll back for now, spend some effort getting some more representative test webapps and try again when we feel more confident in the tests available for this open source version.

@cvlaminck standby and I will see if I can get you a configuration work around that will add org.slf4j. to the contexts server classes, so they are hidden.

**Comment by ludoch** [comment]
Reverting now. Will be built and pushed in less than an hour

**Comment by gregw** [comment]
@cvlaminck I may have a work around for you, as yet untested.   Can you put the following line into your Dockerfile:
```docker
RUN sed -i 'sX</Configure>X<Call name="addServerClass"><Arg>org.slf4j.</Arg></Call><Call name="addServerClass"><Arg>org.apache.log4j.</Arg></Call></Configure>X' $JETTY_BASE/webapps/root.xml
```

That will hide the logging classes added to the server classpath and should allow your slf4j to load again.

**Comment by gregw** [comment]
@cvlaminck Oh I just so @ludoch 's comment, so you will have a reversion soon enough.

Next week I will make sure that we have a test webapp that uses a specific version of slf4j that will be tested before we try #295 again.

**Comment by ludoch** [comment]
revert is pushed as 

gcr.io/google_appengine/jetty9-compat:2016-09-02_00000

and 

gcr.io/google_appengine/jetty9-compat:githubheadasync

**Comment by ludoch** [comment]
You could still test with the previous image located at:

gcr.io/google_appengine/jetty9:2016-09-01_00000

**Comment by cvlaminck** [comment]
Thanks @ludoch, @gregw,

I have test the patch on jetty9:2016-09-01_00000 and everything seems working fine.
However we will stay on githubheadaync for our live application.
