### ISSUE TITLE
webdefault.xml has incomplete security constraints to disable TRACE method

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/appengine-java-vm-runtime#34]
When running a webapp, eg the appengine-java-vm-guestbook-extras, you will see a jetty log line like this:  

2015-08-13 07:58:52.553:WARN:oejs.SecurityHandler:main: ServletContext@c.g.a.v.j.VmRuntimeWebAppContext@5997bce2{/,file:/var/lib/jetty/webapps/root/,STARTING}{/root/} has uncovered http methods for path: /

This is due to the incomplete specification for the security-constraint in webdefault.xml to disable the TRACE method.

The constraint is currently expressed as:
  <security-constraint>
    <web-resource-collection>
      <web-resource-name>Disable TRACE</web-resource-name>
      <url-pattern>/</url-pattern>
      <http-method>TRACE</http-method>
    </web-resource-collection>
    <auth-constraint/>
  </security-constraint>

However, there should be added this:

  <security-constraint>
    <web-resource-collection>
      <web-resource-name>Enable everything but TRACE</web-resource-name>
      <url-pattern>/</url-pattern>
      <http-method-omission>TRACE</http-method-omission>
    </web-resource-collection>
  </security-constraint>

I will add this to the webdefault.xml found in docker/etc, however with the gcloud maven plugin, this is NOT the webdefault.xml that will be used because of quickstart generation. Quickstart seems to use a different webdefault.xml that is inside this file: 

google-cloud-sdk/platform/google_appengine/google/appengine/javamanagedvm/appengine-java-vmruntime/quickstartgenerator.jar

So that jar will need its webdefault.xml updated too.

It is also worthwhile pointing out that I found 2 other webdefault.xml files in the gcloud sdk, both of which should be updated with the extra security constraint, if indeed they are ever used:

/google-cloud-sdk/platform/google_appengine/google/appengine/javamanagedvm/appengine-java-vmruntime/etc/webdefault.xml
/google-cloud-sdk/platform/google_appengine/google/appengine/jettybasesdk/etc/webdefault.xml

**Comment by ludoch** [comment]
Cloud SDK is now up to date with the change.
