### ISSUE TITLE
Needs unit tests

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#40]
The runtime project lacks unit tests.

**Comment by gregw** [comment]
I've started working on some unit tests for the async work that I'm doing, but there are a few moving parts needed to mock up the VmApiProxyEnvironment and associated requests headers.  Rather than spending time reverse engineering a test environment for that, it would be ideal if a sample unit test could be committed to the project on which other unit tests could be based.   So I've assigned to @jboynes as I think you said you had something that could be used?

**Comment by ludoch** [comment]
100% agree and we have those tests internally.
I started last week to remove internal test frameworks usage, and I'm
almost there base a base test env that also mocks the api proxy layer. Last
part needed: you can help me on how to start the embedded jetty code.
Internally we relied on a exploded jetty dir more or less like in prod with
a few XML config files. We can chat at our meeting today.
One we have this base test working, I will commit most/all our unit tests,
that will be a huge milestone!

**Comment by ludoch** [comment]
I started working actively in the unit/system tests we have internal. See the unitests branch PR.

**Comment by ludoch** [comment]
Fixed. We move all our internal tests to the github master and jetty93 branches.
See https://github.com/GoogleCloudPlatform/appengine-java-vm-runtime/commit/f7794c317831e5912f59475c077ea9f6767191ad
