### ISSUE TITLE
pure jetty9 image should support jsp/jstl out of the box

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#54]
Kinda good default for Web Apps.

**Comment by ludoch** [comment]
What other Jetty9 modules should be enabled out of the box?
JNDI? 
Or what is the guideline to easily enable module with a simple dockfile extension? Need documentation.

**Comment by gregw** [comment]
I've recently added such documentation to the official docker image: see https://github.com/docker-library/docs/tree/master/jetty#configuration    Where is the best location for such doco on the pure jetty9 image? in a gce-jetty/README.md ?

I think JSP is a good default module, but I don't think JNDI is.

**Comment by ludoch** [comment]
OK, and the gce-jetty/README can point to the official README.
