### ISSUE TITLE
Pure Jetty9 image: standardize with the /app app location for Google Cloud

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#56]
All the other GAE v2 runtimes seem to use the /app area for adding the user application.

We do it in the jetty9-compat image as well, but I think we should do it in the pure Jetty9 image by adding:
RUN ln -s /var/lib/jetty/webapps/root /app
WORKDIR /app

This way the user web app in /app is registered with the root context (i.e /) at the top of the Jetty server.
So far, we do not anticipate to support multiple web apps served by the same Jetty process. This might change in the future, but the first app and default one should be served at /

**Comment by gregw** [comment]
It may be worthwhile to remove the deployer from the GAEv2 image.  Currently it is scanning $JETTY_BASE/webapps for multiple webapps to deploy.  This can take time, CPU and will probably break if somebody does drop another webapp in there (as it will not be a GAE anointed one).

So two proposals:  

Initially we should remove the deployer from GAE setup and replace with a gae-root-deploy module that does a hard coded (in xml) deployment of only the root webapp.

If eventually multiple webapps are desired, then we should create a gae-deploy module that creates an enhanced deployer that will deploy a normal war or webapp directory as a GAE context.  It there will be no need for a specific context.xml file to create the context as a GAE one.
