### ISSUE TITLE
jetty93 VmRuntimeJettyAuthTest#testAuth_UntrustedInboundIp failing

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#73]
The VmRuntimeJettyAuthTest#testAuth_UntrustedInboundIp test in jetty93 branch is failing. It appears to be trying to contact the real authentication service and hanging.

**Comment by gregw** [comment]
The test has been commented out for now to get a clean build

**Comment by ludoch** [comment]
I think this is because 
    getSecurityHandler().setAuthenticator(new VmAppEngineAuthenticator(
        this, getSecurityHandler().getAuthenticator()));
was removed in VmRuntimeWebAppContext.java

**Comment by ludoch** [comment]
ignore preview comment. still looking
