### ISSUE TITLE
Clean Dockerfile content and features

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-vm-runtime#83]
We have now a layered system for Docker images... Let's do another pass to move things around:

1/ alpn configurable easily in the jdk image
2/ cloud debugger/profiler setup in the jdk image
3/ keep the dor open to things like jrebel or newrelic agents
4/ pure jetty9 image with logs in correct location? (/var/log/app_engine)?
5/ other?

**Comment by gregw** [comment]
2/ has been done in #105
