### ISSUE TITLE
Update Logging to new logging architecture

### ISSUE THREAD

**Issue by gregw** [GoogleCloudPlatform/appengine-java-vm-runtime#91]
Remove the logging that was tied to the delayed commit mechanism and replace with the JSON formatted java logger.

**Comment by gregw** [comment]
@jboynes @ludoch 
In the current VmRuntimeWebAppContext there is the following code 
```
      if (!VmRuntimeUtils.waitForAsyncApiCalls(requestSpecificEnvironment,response)) {
        logger.warning("Timed out or interrupted while waiting for async API calls to complete.");
      }
```
Just before it does the log flushing.  This was in the delayed commit handling, but I have moved it to the onComplete async handling in the async-support branch.

My question is - do we still need to wait for async API calls to complete?  Was this done only so that all the logs could be flushed with the response headers?  Now that we don't delay commit and will support async request handling, is there any reason to delay the end of the request lifecycle until all AsyncAPICalls have completed?     Note that if they do try to use the servlet async API after onComplete, they will get ISE thrown (as they should).

**Comment by jboynes** [comment]
For now I think this is still needed as there is a window between when the response is written and when the request is completed in which API calls could still be made. With the current serving path API calls made in that window may error; this is why we wait for all logging calls to complete before committing the response. There are changes to the serving path that will remove that limitation but those are not yet released.

**Comment by gregw** [comment]
@jboynes but I'm asking this in the context of the async-supported branch where we have already removed the delayed commit.  Thus the response is probably already committed and it is not possible to add headers - as the waitForAsyncApiCalls attempts to do?

**Comment by gregw** [comment]
I've tried rerouted the jetty logging mechanism to java.util.logging only to decide that the jetty JavaUtilLog class is rather deficient (wrong source class/method name for example).     If reimplemented that class and it will be release in 9.3.4 in about a weeks time.

**Comment by gregw** [comment]
This is done in the async-support branch waiting for merge

**Comment by gregw** [comment]
fixed in async-support branch
